function destination(float $lat,float $lon,float $east,float $north):array { $d=hypot($east,$north);if($d<1e-9)return[$lat,$lon];$br=atan2($east,$north);$ad=$d/EARTH;$p=deg2rad($lat);$l=deg2rad($lon);$p2=asin(sin($p)*cos($ad)+cos($p)*sin($ad)*cos($br));$l2=$l+atan2(sin($br)*sin($ad)*cos($p),cos($ad)-sin($p)*sin($p2));return[rad2deg($p2),fmod(rad2deg($l2)+540,360)-180]; }
function winduv(float $speed,float $from):array{$a=deg2rad(fmod($from+180,360));return[sin($a)*$speed,cos($a)*$speed];}
function uvwind(float $e,float $n):array{$s=hypot($e,$n);if($s<1e-9)return[0,0];$tow=fmod(rad2deg(atan2($e,$n))+360,360);return[$s,fmod($tow+180,360)];}
function grid(float $lat,float $lon,float $radiusKm):array{$ld=$radiusKm/111.0;$od=$radiusKm/max(20,111*cos(deg2rad($lat)));$ls=[];$os=[];foreach([-1,-.5,0,.5,1] as $x){$ls[]=$lat+$ld*$x;$os[]=$lon+$od*$x;}return[$ls,$os];}
function meteo(array $lats,array $lons,DateTimeImmutable $start,DateTimeImmutable $end):array {
    $vars=[];foreach(LEVELS as $p){$vars[]="wind_speed_{$p}hPa";$vars[]="wind_direction_{$p}hPa";$vars[]="geopotential_height_{$p}hPa";}$vars[]='precipitation';$vars[]='weather_code';
    $apiEnd=$end; if($end->format('H:i:s')!=='23:00:00') $apiEnd=$end->modify('+1 day');
    $q=http_build_query(['latitude'=>implode(',',array_map(fn($x)=>sprintf('%.4f',$x),$lats)),'longitude'=>implode(',',array_map(fn($x)=>sprintf('%.4f',$x),$lons)),'hourly'=>implode(',',$vars),'start_date'=>$start->format('Y-m-d'),'end_date'=>$apiEnd->format('Y-m-d'),'timezone'=>'UTC','wind_speed_unit'=>'ms']);
    $url=OPEN_METEO.'?'.$q;$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>90,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_USERAGENT=>'Weter-Timeweb/1.0']);$body=curl_exec($ch);$err=curl_error($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($body===false||$code!==200)throw new RuntimeException('Open-Meteo HTTP '.$code.($err?': '.$err:''));$data=json_decode($body,true);if(!is_array($data))throw new RuntimeException('Некорректный ответ Open-Meteo');if(isset($data['hourly']))$data=[$data];$coords=[];foreach($lats as $la)foreach($lons as $lo)$coords[]=[$la,$lo];return['lats'=>$lats,'lons'=>$lons,'cells'=>$data,'coords'=>$coords];
}
function timeIndex(array $times,DateTimeImmutable $target):array{$t=$target->getTimestamp();$first=(new DateTimeImmutable($times[0],new DateTimeZone('UTC')))->getTimestamp();$last=(new DateTimeImmutable(end($times),new DateTimeZone('UTC')))->getTimestamp();if($t<$first||$t>$last)throw new RuntimeException('Время '.iso($target).' выходит за границы загруженного прогноза '.iso(new DateTimeImmutable($times[0],new DateTimeZone('UTC'))).' — '.iso(new DateTimeImmutable(end($times),new DateTimeZone('UTC'))).'.');$n=count($times)-1;if($t===$last)return[$n,$n,0];$lo=0;$hi=$n;while($lo<$hi){$m=intdiv($lo+$hi,2);$mt=(new DateTimeImmutable($times[$m],new DateTimeZone('UTC')))->getTimestamp();if($mt<$t)$lo=$m+1;else$hi=$m;} $i1=$lo;$i0=$i1-1;$a=(new DateTimeImmutable($times[$i0],new DateTimeZone('UTC')))->getTimestamp();$b=(new DateTimeImmutable($times[$i1],new DateTimeZone('UTC')))->getTimestamp();return[$i0,$i1,($t-$a)/max(1,$b-$a)];}
function cellWind(array $cell,float $alt,DateTimeImmutable $when):array{$h=$cell['hourly'];[$i0,$i1,$f]=timeIndex($h['time'],$when);$v=[];foreach(LEVELS as $p){$k="{$p}hPa";if(!isset($h["wind_speed_$k"][$i0],$h["wind_speed_$k"][$i1],$h["wind_direction_$k"][$i0],$h["wind_direction_$k"][$i1],$h["geopotential_height_$k"][$i0],$h["geopotential_height_$k"][$i1]))continue;$s0=(float)$h["wind_speed_$k"][$i0];$s1=(float)$h["wind_speed_$k"][$i1];$d0=(float)$h["wind_direction_$k"][$i0];$d1=(float)$h["wind_direction_$k"][$i1];$z0=(float)$h["geopotential_height_$k"][$i0];$z1=(float)$h["geopotential_height_$k"][$i1];[$e0,$n0]=winduv($s0,$d0);[$e1,$n1]=winduv($s1,$d1);$v[]=[$z0+($z1-$z0)*$f,$e0+($e1-$e0)*$f,$n0+($n1-$n0)*$f];}if(!$v)throw new RuntimeException('Для выбранного времени нет данных ветра.');usort($v,fn($a,$b)=>$a[0]<=>$b[0]);if($alt<=$v[0][0])return uvwind($v[0][1],$v[0][2]);$last=count($v)-1;if($alt>=$v[$last][0])return uvwind($v[$last][1],$v[$last][2]);for($i=1;$i<count($v);$i++){[$z0,$e0,$n0]=$v[$i-1];[$z1,$e1,$n1]=$v[$i];if($alt<=$z1){$f=abs($z1-$z0)<.001?0:($alt-$z0)/($z1-$z0);return uvwind($e0+($e1-$e0)*$f,$n0+($n1-$n0)*$f);}}return uvwind($v[$last][1],$v[$last][2]);}
function interp(array $fc,float $lat,float $lon,float $alt,DateTimeImmutable $when):array{$ls=$fc['lats'];$os=$fc['lons'];sort($ls);sort($os);if($lat<$ls[0]||$lat>$ls[count($ls)-1]||$lon<$os[0]||$lon>$os[count($os)-1])throw new RuntimeException('Траектория вышла за пределы загруженной метеосетки.');$bounds=function($a,$x){$n=count($a);if($x<=$a[0])return[$a[0],$a[0],0];if($x>=$a[$n-1])return[$a[$n-1],$a[$n-1],0];for($i=1;$i<$n;$i++)if($x<=$a[$i])return[$a[$i-1],$a[$i],($x-$a[$i-1])/($a[$i]-$a[$i-1])];return[$a[$n-1],$a[$n-1],0];};[$a,$b,$fy]=$bounds($ls,$lat);[$c,$d,$fx]=$bounds($os,$lon);$find=function($la,$lo)use($fc){$best=null;$bd=INF;foreach($fc['cells'] as $cell){$dd=((float)$cell['latitude']-$la)**2+((float)$cell['longitude']-$lo)**2;if($dd<$bd){$bd=$dd;$best=$cell;}}return$best;};$ws=[];foreach([[$a,$c],[$a,$d],[$b,$c],[$b,$d]] as $p)$ws[]=cellWind($find($p[0],$p[1]),$alt,$when);$uv=array_map(fn($w)=>winduv($w[0],$w[1]),$ws);$e0=$uv[0][0]+($uv[1][0]-$uv[0][0])*$fx;$e1=$uv[2][0]+($uv[3][0]-$uv[2][0])*$fx;$n0=$uv[0][1]+($uv[1][1]-$uv[0][1])*$fx;$n1=$uv[2][1]+($uv[3][1]-$uv[2][1])*$fx;return uvwind($e0+($e1-$e0)*$fy,$n0+($n1-$n0)*$fy);}
function traj(array $p,array $fc):array {
    $lat=(float)$p['lat']; $lon=(float)$p['lon']; $alt=(float)($p['start_altitude']??0);
    $as=(float)($p['ascent_rate']??5); $max=(float)($p['max_altitude']??10000);
    $hours=(float)($p['duration_hours']??24); $step=(float)($p['step_minutes']??5)*60;
    $t=utc($p['start_time']); $total=$hours*3600; $n=(int)ceil($total/$step); $out=[];
    for($i=0;$i<=$n;$i++){
        $elapsed=min($i*$step,$total); $when=$t->modify('+'.(int)round($elapsed).' seconds');
        $out[]=['time'=>iso($when),'lat'=>$lat,'lon'=>$lon,'altitude'=>$alt]; if($elapsed >= $total) break;
        $dt=min($step,$total-$elapsed);
        $der=function(float $la,float $lo,float $aa,DateTimeImmutable $tm)use($fc,$as,$max):array{
            $w=interp($fc,$la,$lo,$aa,$tm); [$e,$n]=winduv($w[0],$w[1]); return[$e,$n,$aa<$max?$as:0.0];
        };
        $k1=$der($lat,$lon,$alt,$when);
