<?php
function point(float $lat,float $lon):array{return['lat'=>$lat,'lon'=>$lon];}
function parsePoint(array $a,string $name):array{if(!isset($a['lat'],$a['lon']))throw new RuntimeException("Не указана точка $name");return[(float)$a['lat'],(float)$a['lon']];}
function ringPoints(float $lat,float $lon,float $radius,int $rings=2,int $per=12):array{$out=[[$lat,$lon]];for($r=1;$r<=$rings;$r++){ $count=max(8,$per*$r);for($i=0;$i<$count;$i++){ $a=2*M_PI*$i/$count;[$la,$lo]=destination($lat,$lon,sin($a)*$radius*$r/$rings,cos($a)*$radius*$r/$rings);$out[]=[$la,$lo]; }}return$out;}
function segCircle(array $a,array $b,array $c,float $r):array{$lat0=deg2rad($c[0]);$sx=EARTH*cos($lat0);$sy=EARTH;$ax=deg2rad($a[1]-$c[1])*$sx;$ay=deg2rad($a[0]-$c[0])*$sy;$bx=deg2rad($b[1]-$c[1])*$sx;$by=deg2rad($b[0]-$c[0])*$sy;$dx=$bx-$ax;$dy=$by-$ay;$aa=$dx*$dx+$dy*$dy;if($aa<1e-12)return[$ax*$ax+$ay*$ay<=$r*$r,1.0];$t=clamp(-($ax*$dx+$ay*$dy)/$aa,0,1);$px=$ax+$t*$dx;$py=$ay+$t*$dy;$d2=$px*$px+$py*$py;if($d2>$r*$r)return[false,0];$half=sqrt(max(0,$r*$r-$d2)/$aa);$lo=max(0,$t-$half);$hi=min(1,$t+$half);return[true,$hi-$lo];}
function targetHit(array $a,array $b,array $target,float $radius):array{return segCircle([$a['lat'],$a['lon']],[$b['lat'],$b['lon']],$target,$radius);}
function truncateTarget(array $tr,float $tlat,float $tlon,float $radius):array{$out=[];if(!$tr)return$out;$target=[$tlat,$tlon];$out[]=$tr[0];for($i=1;$i<count($tr);$i++){ $a=$tr[$i-1];$b=$tr[$i];$hit=$targetHit($a,$b,$target,$radius);if($hit[0]){[$ok,$fraction]=segCircle([$a['lat'],$a['lon']],[$b['lat'],$b['lon']],$target,$radius);$f=max(0,min(1,$fraction>0?0.5:0));$d0=hav($a['lat'],$a['lon'],$tlat,$tlon);$d1=hav($b['lat'],$b['lon'],$tlat,$tlon);if(abs($d0-$d1)>1e-9)$f=clamp(($d0-$radius)/($d0-$d1),0,1);$ta=utc($a['time']);$tb=utc($b['time']);$dt=$tb->getTimestamp()-$ta->getTimestamp();$out[]=['time'=>iso($ta->modify('+'.(int)round($dt*$f).' seconds')),'lat'=>$a['lat']+($b['lat']-$a['lat'])*$f,'lon'=>$a['lon']+($b['lon']-$a['lon'])*$f,'altitude'=>$a['altitude']+($b['altitude']-$a['altitude'])*$f];return$out;} $out[]=$b;}return$out;}
function surfaceShear(array $fc,float $lat,float $lon,DateTimeImmutable $when,float $top):array{$surface=interp($fc,$lat,$lon,10,$when)[0];[$eu,$nu]=winduv(...interp($fc,$lat,$lon,10,$when));[$et,$nt]=winduv(...interp($fc,$lat,$lon,max(100,$top),$when));return[$surface,hypot($et-$eu,$nt-$nu)/max(1,$top-10)];}
function weatherHazard(array $fc,array $tr,float $limit):bool{foreach($tr as $p){$best=null;$bd=INF;foreach($fc['cells'] as $c){$d=((float)$c['latitude']-$p['lat'])**2+((float)$c['longitude']-$p['lon'])**2;if($d<$bd){$bd=$d;$best=$c;}}if(!$best)continue;$h=$best['hourly'];if(!isset($h['time']))continue;$times=$h['time'];$pt=utc($p['time'])->getTimestamp();$idx=0;$mind=INF;foreach($times as $i=>$tm){$d=abs(utc($tm)->getTimestamp()-$pt);if($d<$mind){$mind=$d;$idx=$i;}}$code=$h['weather_code'][$idx]??null;$rain=$h['precipitation'][$idx]??0;if($code!==null&&in_array((int)$code,[95,96,99],true))return true;if((float)$rain>$limit)return true;}return false;}
function perturbForecast(array $fc,int $seed,float $sigma):array{mt_srand($seed);$out=$fc;foreach($out['cells'] as &$cell){$h=$cell['hourly'];foreach(LEVELS as $p){$k="{$p}hPa";$sk="wind_speed_$k";$dk="wind_direction_$k";if(!isset($h[$sk],$h[$dk]))continue;foreach($h[$sk] as $i=>$speed){$dir=$h[$dk][$i]??null;if($speed===null||$dir===null)continue;[$e,$n]=winduv((float)$speed,(float)$dir);$e+=gauss()*$sigma;$n+=gauss()*$sigma;$h[$sk][$i]=hypot($e,$n);$h[$dk][$i]=uvwind($e,$n)[1];}}$cell['hourly']=$h;}unset($cell);mt_srand();return$out;}
function gauss():float{$u=max(1e-12,mt_rand()/mt_getrandmax());$v=max(1e-12,mt_rand()/mt_getrandmax());return sqrt(-2*log($u))*cos(2*M_PI*$v);}
function backSolve(array $fc,float $dlat,float $dlon,float $alt,DateTimeImmutable $dt,float $duration,float $step,float $startAlt,float $ascent,float $windBiasE=0,float $windBiasN=0):array{$duration=min($duration,48.0);$step=abs($step)*60;$remaining=$duration*3600;$elapsed=0.0;$lat=$dlat;$lon=$dlon;$z=max($startAlt,$alt);$when=$dt;$maxAlt=max(10000.0,$z);$plateau=$z>=0.95*$maxAlt;$ascentTime=$plateau?max(0,($maxAlt-$startAlt)/max(.01,$ascent)):0;$plateauDuration=$plateau?max(0,$duration*3600-$ascentTime):0;$out=[];$wind=function(float $la,float $lo,float $aa,DateTimeImmutable $tm)use($fc,$windBiasE,$windBiasN):array{$w=interp($fc,$la,$lo,$aa,$tm);$factor=.65+.35*clamp($aa/10000,0,1);[$e,$n]=winduv($w[0],$w[1]);return[$e+$windBiasE*$factor,$n+$windBiasN*$factor];};$append=function()use(&$out,$lat,$lon,$z,$when,$wind){[$e,$n]=$wind($lat,$lon,$z,$when);[$speed,$dir]=uvwind($e,$n);$out[]=['time'=>iso($when),'lat'=>$lat,'lon'=>$lon,'altitude'=>$z,'u_mps'=>$e,'v_mps'=>$n,'wind_speed_mps'=>$speed,'wind_direction'=>$dir];};$append();while($remaining>1e-9&&$z>$startAlt+1e-6){$h=min($step,$remaining);$d=-$h;$vertical=function(float $e)use($z,$startAlt,$plateau,$plateauDuration,$ascent):float{if($z<=$startAlt+1e-6)return 0;if($plateau&&$e<$plateauDuration)return 0;return$ascent;};[$k1e,$k1n]=$wind($lat,$lon,$z,$when);$k1z=$vertical($elapsed);$a2=max($startAlt,$z+$k1z*$d/2);[$la2,$lo2]=destination($lat,$lon,$k1e*$d/2,$k1n*$d/2);$t2=$when->modify((string)round($d/2).' seconds');[$k2e,$k2n]=$wind($la2,$lo2,$a2,$t2);$k2z=(!$plateau||$elapsed+$h/2>=$plateauDuration)?$ascent:0;$a3=max($startAlt,$z+$k2z*$d/2);[$la3,$lo3]=destination($lat,$lon,$k2e*$d/2,$k2n*$d/2);[$k3e,$k3n]=$wind($la3,$lo3,$a3,$t2);$k3z=(!$plateau||$elapsed+$h/2>=$plateauDuration)?$ascent:0;$a4=max($startAlt,$z+$k3z*$d);[$la4,$lo4]=destination($lat,$lon,$k3e*$d,$k3n*$d);$t4=$when->modify((string)round($d).' seconds');[$k4e,$k4n]=$wind($la4,$lo4,$a4,$t4);$k4z=(!$plateau||$elapsed+$h>=$plateauDuration)?$ascent:0;$ll=destination($lat,$lon,$d*($k1e+2*$k2e+2*$k3e+$k4e)/6,$d*($k1n+2*$k2n+2*$k3n+$k4n)/6);$lat=$ll[0];$lon=$ll[1];$z=max($startAlt,$z+$d*($k1z+2*$k2z+2*$k3z+$k4z)/6);$when=$when->modify((string)round($d).' seconds');$elapsed+=$h;$remaining-=$h;$append();}return$out;}
function randNormal():float{$u=max(1e-12,mt_rand()/mt_getrandmax());$v=max(1e-12,mt_rand()/mt_getrandmax());return sqrt(-2*log($u))*cos(2*M_PI*$v);}
function backEnsemble(array $fc,float $dlat,float $dlon,float $alt,DateTimeImmutable $dt,float $hours,float $step,float $ascent,int $members,float $windSigma=1.5,float $timeSigma=60,float $altSigma=50):array{mt_srand(42);$trajectories=[];$launches=[];for($i=0;$i<$members;$i++){try{$t=$dt->modify((string)round(randNormal()*$timeSigma).' seconds');$z=max(0,$alt+randNormal()*$altSigma);$a=max(.2,$ascent+randNormal()*.7);$du=randNormal()*$windSigma;$dv=randNormal()*$windSigma;$tr=backSolve($fc,$dlat,$dlon,$z,$t,$hours,$step,0,$a,$du,$dv);if($tr){$trajectories[]=$tr;$launches[]=$tr[count($tr)-1];}}catch(Throwable $e){}}mt_srand();if(!$launches)throw new RuntimeException('Не удалось построить ни одной обратной траектории.');$clat=0;$clon=0;foreach($launches as $q){$clat+=$q['lat'];$clon+=$q['lon'];}$clat/=count($launches);$clon/=count($launches);$dist=[];foreach($launches as $q)$dist[]=hav($clat,$clon,$q['lat'],$q['lon']);sort($dist);$n=count($dist);$zones=[];foreach([.5,.8,.95] as $q){$idx=min($n-1,(int)floor($q*($n-1)));$zones[]=['probability'=>$q,'radius_m'=>$dist[$idx],'center_lat'=>$clat,'center_lon'=>$clon];}$best=0;for($i=1;$i<count($launches);$i++)if($dist[$i]<$dist[$best])$best=$i;return['trajectories'=>$trajectories,'launch_estimate'=>$launches[$best],'zones'=>$zones,'valid_members'=>$n,'ensemble_size'=>$members];}
function api():never {
    $action=$_GET['api']??'';if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='health')json_out(['status'=>'ok','service'=>'weter-timeweb','version'=>'1.3']);if($_SERVER['REQUEST_METHOD']!=='POST')fail('API endpoint');$p=req();
    try{
        if($action==='trajectory'){[$lat,$lon]=parsePoint($p['start']??$p,'старта');$st=utc((string)$p['start_time']);$hours=(float)($p['duration_hours']??24);$end=$st->modify('+'.(int)ceil($hours*3600).' seconds');[$ls,$os]=grid($lat,$lon,forecastRadius($hours));$fc=meteo($ls,$os,$st,$end);$tr=traj(['lat'=>$lat,'lon'=>$lon,'start_time'=>iso($st),'start_altitude'=>(float)($p['start_altitude']??0),'ascent_rate'=>(float)($p['ascent_rate']??5),'max_altitude'=>(float)($p['max_altitude']??10000),'duration_hours'=>$hours,'step_minutes'=>(float)($p['step_minutes']??5)],$fc);json_out(['status'=>'ok','trajectory'=>$tr,'points'=>$tr]);}
        if($action==='backtrajectory'){[$dlat,$dlon]=parsePoint($p['detection']??[],'обнаружения');$dt=utc((string)$p['detection_time']);$hours=(float)($p['duration_hours']??4);$step=(float)($p['step_minutes']??1);$as=(float)($p['ascent_rate']??5);$alt=(float)$p['altitude'];$start=$dt->modify('-'.(int)ceil($hours*3600).' seconds');[$ls,$os]=grid($dlat,$dlon,forecastRadius($hours));$fc=meteo($ls,$os,$start,$dt);$members=max(20,min(200,(int)($p['members']??150)));$ens=backEnsemble($fc,$dlat,$dlon,$alt,$dt,$hours,$step,$as,$members,(float)($p['wind_sigma_mps']??1.5),(float)($p['detection_time_sigma_s']??60),(float)($p['altitude_sigma_m']??50));$launch=$ens['launch_estimate'];$tr=$ens['trajectories'][0]??[];json_out(['status'=>'ok','result'=>['detection'=>['lat'=>$dlat,'lon'=>$dlon,'altitude'=>$alt,'time'=>iso($dt)],'launch_estimate'=>$launch,'zones'=>$ens['zones'],'ensemble_size'=>$ens['ensemble_size'],'valid_members'=>$ens['valid_members'],'trajectory'=>$tr,'points'=>$tr,'trajectories'=>$ens['trajectories']]]);}
        if($action==='favorable'){
            [$tlat,$tlon]=parsePoint($p['target']??[],'цели');[$clat,$clon]=parsePoint($p['launch_center']??[],'центра запуска');$ss=utc((string)$p['search_start']);$se=utc((string)$p['search_end']);if($se<=$ss)throw new RuntimeException('Конец периода должен быть позже начала.');$hours=(float)($p['duration_hours']??5);$step=(float)($p['step_minutes']??2);$rad=(float)($p['launch_radius_m']??1000);$targetRad=(float)($p['target_radius_m']??5000);$timeStep=(float)($p['time_step_hours']??1);$surfaceLimit=(float)($p['surface_wind_limit_mps']??10);$shearLimit=(float)($p['shear_limit_s_inv']??0.002);$rainLimit=(float)($p['precipitation_limit_mm']??5);$ensembleMembers=max(1,min(200,(int)($p['ensemble_members']??30)));$ensembleSigma=(float)($p['ensemble_wind_sigma_mps']??1.5);$points=ringPoints($clat,$clon,$rad,2,12);$found=[];$times=[];$t=$ss;while($t<=$se){$times[]=$t;$t=$t->modify('+'.(int)round($timeStep*3600).' seconds');}
            foreach($times as $launchTime){$forecastEnd=$launchTime->modify('+'.(int)ceil($hours*3600).' seconds');[$ls,$os]=grid(($clat+$tlat)/2,($clon+$tlon)/2,forecastRadius($hours)+$rad/1000);$fc=meteo($ls,$os,$launchTime,$forecastEnd);foreach($points as $lp){$params=['lat'=>$lp[0],'lon'=>$lp[1],'start_time'=>iso($launchTime),'start_altitude'=>(float)($p['start_altitude']??0),'ascent_rate'=>(float)($p['ascent_rate']??5),'max_altitude'=>(float)($p['max_altitude']??9000),'duration_hours'=>$hours,'step_minutes'=>$step];$tr=traj($params,$fc);$min=INF;$idx=null;foreach($tr as $j=>$pt){$d=hav($pt['lat'],$pt['lon'],$tlat,$tlon);if($d<$min){$min=$d;$idx=$j;}}$hit=false;for($j=1;$j<count($tr);$j++){if(targetHit($tr[$j-1],$tr[$j],[$tlat,$tlon],$targetRad)[0]){$hit=true;$idx=$j;break;}}if(!$hit||$idx===null)continue;[$surface,$shear]=surfaceShear($fc,$lp[0],$lp[1],$launchTime,(float)($params['max_altitude']));$hazard=weatherHazard($fc,$tr,$rainLimit);if($surface>$surfaceLimit||$shear>$shearLimit||$hazard)continue;$cut=truncateTarget($tr,$tlat,$tlon,$targetRad);$found[]=['launch_time'=>iso($launchTime),'launch_point'=>point($lp[0],$lp[1]),'min_distance_to_target_m'=>round($min,1),'recommended_time'=>iso($launchTime),'score'=>round($min/max(100,$targetRad)+$surface/max(.1,$surfaceLimit)*.05+$shear/max(1e-9,$shearLimit)*.05,4),'surface_wind_mps'=>round($surface,2),'shear_s_inv'=>$shear,'hazard_hit'=>false,'restricted_hit'=>false,'ensemble_success_rate'=>0,'ensemble_median_distance_m'=>0,'ensemble_p90_distance_m'=>0,'trajectory'=>$cut,'closest_point'=>$tr[$idx]];}}
            usort($found,fn($a,$b)=>$a['score']<=>$b['score']);$targetCount=min(count($found),max(24,(int)ceil(count($found)*.2)));$selected=array_slice($found,0,$targetCount);$seen=[];foreach($selected as $c)$seen[$c['launch_time']]=true;foreach($found as $c){if(count($selected)>=min(count($found),$targetCount+count($times)))break;if(!isset($seen[$c['launch_time']])){$selected[]=$c;$seen[$c['launch_time']]=true;}}
            foreach($selected as &$c){$dists=[];$success=0;$launchDt=utc($c['launch_time']);$efEnd=$launchDt->modify('+'.(int)ceil($hours*3600).' seconds');[$els,$eos]=grid(($clat+$tlat)/2,($clon+$tlon)/2,forecastRadius($hours)+$rad/1000);$candidateFc=meteo($els,$eos,$launchDt,$efEnd);$baseParams=['lat'=>$c['launch_point']['lat'],'lon'=>$c['launch_point']['lon'],'start_time'=>$c['launch_time'],'start_altitude'=>(float)($p['start_altitude']??0),'ascent_rate'=>(float)($p['ascent_rate']??5),'max_altitude'=>(float)($p['max_altitude']??9000),'duration_hours'=>$hours,'step_minutes'=>$step];for($m=0;$m<$ensembleMembers;$m++){try{$efc=$m===0?$candidateFc:perturbForecast($candidateFc,1009*$m+17,$ensembleSigma);$et=traj($baseParams,$efc);$ed=INF;$ehit=false;for($j=0;$j<count($et);$j++){$ed=min($ed,hav($et[$j]['lat'],$et[$j]['lon'],$tlat,$tlon));if($j>0&&targetHit($et[$j-1],$et[$j],[$tlat,$tlon],$targetRad)[0])$ehit=true;}if(is_finite($ed)){$dists[]=$ed;if($ehit)$success++;}}catch(Throwable $e){}}if($dists){sort($dists);$n=count($dists);$c['ensemble_success_rate']=$success/$n;$c['ensemble_median_distance_m']=$dists[intdiv($n,2)];$c['ensemble_p90_distance_m']=$dists[min($n-1,(int)floor(.9*($n-1)))];$c['score']=$c['ensemble_p90_distance_m']/max(100,$targetRad)-$c['ensemble_success_rate']*2+$c['min_distance_to_target_m']/max(100,$targetRad);}}
            unset($c);usort($selected,fn($a,$b)=>$a['score']<=>$b['score']);$found=$selected;json_out(['status'=>'ok','count'=>count($found),'windows'=>$found,'processed'=>count($times),'total'=>count($times)]);
        }
        fail('Неизвестный API endpoint',404);
    }catch(Throwable $e){json_out(['status'=>'error','detail'=>$e->getMessage()],502);}
}
if(isset($_GET['api']))api();
?>
