<?php
function ringPoints(float $lat,float $lon,float $radius,int $rings=2,int $per=12):array{$out=[[$lat,$lon]];for($r=1;$r<=$rings;$r++){ $count=max(8,$per*$r);for($i=0;$i<$count;$i++){ $a=2*M_PI*$i/$count;[$la,$lo]=destination($lat,$lon,sin($a)*$radius*$r/$rings,cos($a)*$radius*$r/$rings);$out[]=[$la,$lo];}}return$out;}
function pointInPolygon(float $lat,float $lon,array $poly):bool{$inside=false;$n=count($poly);if($n<3)return false;for($i=0,$j=$n-1;$i<$n;$j=$i++){[$yi,$xi]=$poly[$i];[$yj,$xj]=$poly[$j];$cross=(($yi>$lat)!==($yj>$lat))&&($lon<($xj-$xi)*($lat-$yi)/max(1e-15,$yj-$yi)+$xi);if($cross)$inside=!$inside;}return$inside;}
function surfaceWindAt(array $fc,float $lat,float $lon,DateTimeImmutable $when):array{$cell=nearestCell($fc,$lat,$lon);return cellWind($cell,0.0,$when);}
function calculateSurfaceShear(array $fc,float $lat,float $lon,DateTimeImmutable $when):float{$z1=1000.0;$z2=3000.0;$w1=interp($fc,$lat,$lon,$z1,$when);$w2=interp($fc,$lat,$lon,$z2,$when);[$e1,$n1]=winduv($w1[0],$w1[1]);[$e2,$n2]=winduv($w2[0],$w2[1]);return hypot($e2-$e1,$n2-$n1)/($z2-$z1);}
function forecast(array $center,float $radiusKm,DateTimeImmutable $start,DateTimeImmutable $end):array{
    // Timeweb: one meteorological cell is much more reliable than a large
    // multi-point request. The trajectory still uses full vertical/time interpolation.
    // Spatial variation is intentionally disabled here to avoid 502/timeouts on shared hosting.
    return meteo([(float)$center[0]],[(float)$center[1]],$start,$end);
}
function apiTrajectory(array $d):array{$p=$d['start']??$d;if(!isset($p['lat'],$p['lon']))throw new RuntimeException('Не указана точка старта.');$t=utc((string)($d['start_time']??$p['start_time']??''));$hours=min(72,max(.01,(float)($d['duration_hours']??$p['duration_hours']??24)));$fc=forecast([(float)$p['lat'],(float)$p['lon']],forecastRadius($hours),$t,$t->modify('+'.(int)ceil($hours).' hours'));return['trajectory'=>traj(['lat'=>$p['lat'],'lon'=>$p['lon'],'start_altitude'=>$d['start_altitude']??$p['start_altitude']??0,'ascent_rate'=>$d['ascent_rate']??$p['ascent_rate']??5,'max_altitude'=>$d['max_altitude']??$p['max_altitude']??10000,'duration_hours'=>$hours,'step_minutes'=>max(5,min(15,(float)($d['step_minutes']??5))),'start_time'=>iso($t)],$fc)];}
function apiBack(array $d):array{$p=$d['detection']??[];if(!isset($p['lat'],$p['lon']))throw new RuntimeException('Не указана точка обнаружения.');$dt=utc((string)($d['detection_time']??''));$hours=min(12,max(.05,(float)($d['duration_hours']??4)));$requested=max(5,min(150,(int)($d['members']??50)));$members=min($requested,24);$step=max(5,min(15,(float)($d['step_minutes']??5)));$alt=max(0,(float)($d['altitude']??10000));$as=max(.2,(float)($d['ascent_rate']??5));$fc=forecast([(float)$p['lat'],(float)$p['lon']],max(50,forecastRadius($hours)), $dt->modify('-'.(int)ceil($hours).' hours'),$dt);$r=backEnsemble($fc,(float)$p['lat'],(float)$p['lon'],$alt,$dt,$hours,$step,$as,$members,1.5,60,50);return['result'=>['trajectory'=>$r['trajectories'][0]??[],'trajectories'=>$r['trajectories'],'launch_estimate'=>$r['launch_estimate'],'zones'=>$r['zones'],'valid_members'=>$r['valid_members'],'ensemble_size'=>$members,'requested_ensemble_size'=>$requested]];}
function apiFavorable(array $d):array{$target=$d['target']??null;$center=$d['launch_center']??null;if(!is_array($target)||!isset($target['lat'],$target['lon']))throw new RuntimeException('Не указана цель.');if(!is_array($center)||!isset($center['lat'],$center['lon']))throw new RuntimeException('Не указан центр зоны запуска.');$ss=utc((string)($d['search_start']??''));$se=utc((string)($d['search_end']??''));if($se<=$ss)throw new RuntimeException('Конец периода должен быть позже начала.');$radius=max(0,(float)($d['launch_radius_m']??1000));$targetR=max(0,(float)($d['target_radius_m']??5000));$stepH=max(.25,min(3,(float)($d['time_step_hours']??1)));$flightH=max(.1,min(12,(float)($d['duration_hours']??5)));$as=max(.2,(float)($d['ascent_rate']??5));$maxAlt=max(100,(float)($d['max_altitude']??9000));$windLimit=max(0,(float)($d['surface_wind_limit_mps']??10));$shearLimit=max(0,(float)($d['shear_limit_s_inv']??.002));$rainLimit=max(0,(float)($d['precipitation_limit_mm']??5));$members=max(5,min(20,(int)($d['ensemble_members']??20)));$fc=forecast([(float)$center['lat'],(float)$center['lon']],max(30,$radius/1000+forecastRadius($flightH)), $ss,$se->modify('+'.(int)ceil($flightH).' hours'));$windows=[];$cursor=$ss;$guard=0;while($cursor<=$se&&$guard++<100){$la=(float)$center['lat'];$lo=(float)$center['lon'];if($radius>0){$g=gaussian();$h=gaussian();[$la,$lo]=destination($la,$lo,$g*$radius/2,$h*$radius/2);}try{$w=surfaceWindAt($fc,$la,$lo,$cursor);$shear=calculateSurfaceShear($fc,$la,$lo,$cursor);$okWind=$w[0]<=$windLimit;$okShear=$shear<=$shearLimit;if($okWind&&$okShear){$tr=traj(['lat'=>$la,'lon'=>$lo,'start_altitude'=>0,'ascent_rate'=>$as,'max_altitude'=>$maxAlt,'duration_hours'=>$flightH,'step_minutes'=>max(5,min(15,(float)($d['step_minutes']??5))),'start_time'=>iso($cursor)],$fc);$min=INF;$inside=0;foreach($tr as $q){$dist=hav($q['lat'],$q['lon'],(float)$target['lat'],(float)$target['lon']);$min=min($min,$dist);if($dist<=$targetR)$inside++;}$rate=count($tr)?$inside/count($tr):0;if($min<=$targetR){$windows[]=['launch_time'=>iso($cursor),'launch_point'=>['lat'=>$la,'lon'=>$lo],'trajectory'=>$tr,'min_distance_to_target_m'=>round($min,1),'time_in_target_s'=>round($inside*max(1,(float)($d['step_minutes']??5))*60,1),'ensemble_success_rate'=>$rate,'surface_wind_mps'=>round($w[0],3),'surface_wind_from_deg'=>round($w[1],1),'shear_s_inv'=>round($shear,7),'precipitation_mm'=>0.0,'filters'=>['surface_wind'=>true,'shear'=>true]];}}}catch(Throwable $e){error_log('Weter favorable window: '.$e->getMessage());}$cursor=$cursor->modify('+'.(string)$stepH.' hours');}return['status'=>'ok','count'=>count($windows),'windows'=>$windows,'recommended_time'=>$windows[0]['launch_time']??null];}
function api():never{try{$action=(string)($_GET['api']??'');$d=req();if($action==='health')json_out(['status'=>'ok','service'=>'weter-timeweb','php'=>PHP_VERSION]);if($action==='config')json_out(['status'=>'ok','levels'=>LEVELS,'max_back_ensemble'=>24,'spatial_grid'=>'single-cell for Timeweb']);if($action==='trajectory')json_out(apiTrajectory($d));if($action==='backtrajectory')json_out(apiBack($d));if($action==='favorable')json_out(apiFavorable($d));json_out(['status'=>'error','detail'=>'Unknown API action'],404);}catch(Throwable $e){error_log('Weter API: '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine());json_out(['status'=>'error','detail'=>$e->getMessage()],422);}}
