/* Weter browser runtime: client-side fallback/bridge for Timeweb. */
(()=>{
'use strict';
const EARTH=6371000,RD=287.05,LEVELS=[1000,975,950,925,900,850,800,700,600,500,400,300,250,200];
const rad=x=>x*Math.PI/180,deg=x=>x*180/Math.PI,cl=(x,a,b)=>Math.max(a,Math.min(b,x));
const sleep=()=>new Promise(r=>setTimeout(r,0));
function mv(lat,lon,e,n){return[lat+deg(n/EARTH),((lon+deg(e/(EARTH*Math.max(.1,Math.cos(rad(lat)))))+540)%360)-180]}
function uv(s,d){const a=rad((d+180)%360);return[s*Math.sin(a),s*Math.cos(a)]}
function gauss(){let u=Math.max(1e-12,Math.random()),v=Math.max(1e-12,Math.random());return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function grid(lat,lon,r){const ld=r/111,od=r/Math.max(20,111*Math.cos(rad(lat))),a=[-1,-.5,0,.5,1];return{lats:a.map(x=>lat+x*ld),lons:a.map(x=>lon+x*od)}}
const vars=()=>LEVELS.flatMap(p=>['wind_speed_'+p+'hPa','wind_direction_'+p+'hPa','temperature_'+p+'hPa','geopotential_height_'+p+'hPa']).concat(['precipitation','weather_code']).join(',');
async function wx(lat,lon,rkm,start,end){const g=grid(lat,lon,rkm),age=(Date.now()-start.getTime())/86400000;let u='https://api.open-meteo.com/v1/forecast',p={past_days:Math.min(92,Math.max(1,Math.floor(Math.max(0,age))+3)),forecast_days:2};if(age>5.5){u='https://archive-api.open-meteo.com/v1/archive';p={start_date:start.toISOString().slice(0,10),end_date:end.toISOString().slice(0,10)}}Object.assign(p,{latitude:g.lats.join(','),longitude:g.lons.join(','),hourly:vars(),timezone:'UTC',wind_speed_unit:'ms',temperature_unit:'celsius'});const q=await fetch(u+'?'+new URLSearchParams(p));if(!q.ok)throw Error('Open-Meteo HTTP '+q.status);let c=await q.json();if(!Array.isArray(c))c=[c];return{cells:c,lats:g.lats,lons:g.lons,times:c[0].hourly.time.map(x=>new Date(x+'Z'))}}
function ti(ts,t){if(t<=ts[0])return[0,0,0];if(t>=ts.at(-1)){const n=ts.length-1;return[n,n,0]}let i=1;while(i<ts.length&&ts[i]<t)i++;return[i-1,i,(t-ts[i-1])/(ts[i]-ts[i-1])]}
function node(w,c,z,t){const h=c.hourly,[i,j,f]=ti(w.times,t),v=[];for(const p of LEVELS){const s=h['wind_speed_'+p+'hPa'],d=h['wind_direction_'+p+'hPa'],T=h['temperature_'+p+'hPa'],g=h['geopotential_height_'+p+'hPa'];if(!s||!d||!T||!g||s[i]==null||s[j]==null||g[i]==null||g[j]==null)continue;const [u0,n0]=uv(+s[i],+d[i]),[u1,n1]=uv(+s[j],+d[j]);v.push([+g[i]+(+g[j]-+g[i])*f,u0+(u1-u0)*f,n0+(n1-n0)*f,+T[i]+(+T[j]-+T[i])*f+273.15,p*100])}v.sort((a,b)=>a[0]-b[0]);if(!v.length)throw Error('Нет pressure-level данных для выбранного времени');if(z<=v[0][0])return v[0].slice(1);if(z>=v.at(-1)[0])return v.at(-1).slice(1);for(let k=1;k<v.length;k++)if(z<=v[k][0]){const q=(z-v[k-1][0])/Math.max(1,v[k][0]-v[k-1][0]);return[v[k-1][1]+(v[k][1]-v[k-1][1])*q,v[k-1][2]+(v[k][2]-v[k-1][2])*q,v[k-1][3]+(v[k][3]-v[k-1][3])*q,Math.exp(Math.log(v[k-1][4])+(Math.log(v[k][4])-Math.log(v[k-1][4]))*q)]}}
function st(w,lat,lon,z,t){const ix=(a,x)=>{if(x<=a[0])return[0,0,0];if(x>=a.at(-1)){let n=a.length-1;return[n,n,0]}let i=1;while(a[i]<x)i++;return[i-1,i,(x-a[i-1])/(a[i]-a[i-1])]},[y0,y1,fy]=ix(w.lats,lat),[x0,x1,fx]=ix(w.lons,lon),at=(y,x)=>w.cells[y*5+x]||w.cells[0],a=node(w,at(y0,x0),z,t),b=node(w,at(y0,x1),z,t),c=node(w,at(y1,x0),z,t),d=node(w,at(y1,x1),z,t),bl=q=>q[0]*(1-fx)*(1-fy)+q[1]*fx*(1-fy)+q[2]*(1-fx)*fy+q[3]*fx*fy;return[bl([a[0],b[0],c[0],d[0]]),bl([a[1],b[1],c[1],d[1]]),bl([a[2],b[2],c[2],d[2]]),bl([a[3],b[3],c[3],d[3]]),bl([a[4],b[4],c[4],d[4]])]}
function integrate(w,p,backward=false){let lat=p.lat,lon=p.lon,z=p.alt,t=new Date(p.time),elapsed=0,out=[],total=p.duration*3600,dt=Math.max(1,p.step*60);const f=(la,lo,zz,tt)=>{const s=st(w,la,lo,zz,tt),as=p.ascent;return[backward?-s[0]:s[0],backward?-s[1]:s[1],backward?-Math.max(.5,as):Math.min(as,p.maxAlt>zz?as:0)]};while(elapsed<total&&z>0){const h=Math.min(dt,total-elapsed),sg=backward?-1:1,k1=f(lat,lon,z,t),a=mv(lat,lon,k1[0]*h/2,k1[1]*h/2),k2=f(a[0],a[1],cl(z+k1[2]*h/2,0,p.maxAlt),new Date(t.getTime()+sg*h*500)),b=mv(lat,lon,k2[0]*h/2,k2[1]*h/2),k3=f(b[0],b[1],cl(z+k2[2]*h/2,0,p.maxAlt),new Date(t.getTime()+sg*h*500)),c=mv(lat,lon,k3[0]*h,k3[1]*h),k4=f(c[0],c[1],cl(z+k3[2]*h,0,p.maxAlt),new Date(t.getTime()+sg*h*1000));[lat,lon]=mv(lat,lon,h*(k1[0]+2*k2[0]+2*k3[0]+k4[0])/6,h*(k1[1]+2*k2[1]+2*k3[1]+k4[1])/6);z=cl(z+h*(k1[2]+2*k2[2]+2*k3[2]+k4[2])/6,0,p.maxAlt);t=new Date(t.getTime()+sg*h*1000);elapsed+=h;out.push({time:t.toISOString(),lat,lon,altitude_m:z,u_mps:k1[0],v_mps:k1[1],wind_speed_mps:Math.hypot(k1[0],k1[1])});if(backward&&z<=10)break}return out}
function status2(s,e=false){if(typeof window.status==='function')window.status(s,e)}function progress2(x){if(typeof window.progress==='function')window.progress(x,true)}
async function direct(){clearLines();status2('Прямая: загрузка 5×5 метеосетки…');progress2(3);const p={lat:+dlat.value,lon:+dlon.value,alt:+dalt.value,ascent:+das.value,maxAlt:+dmax.value,duration:+dh.value,step:5,time:new Date(dtime.value)},w=await wx(p.lat,p.lon,Math.max(8,p.duration*25),new Date(p.time.getTime()-3600000),new Date(p.time.getTime()+p.duration*3600000));const pts=integrate(w,p);line(pts,'#1f6feb',3);fitAll();showResult('<b>Точек:</b> '+pts.length+'<br><b>Источник:</b> браузер · Open-Meteo · 5×5 · RK4');status2('Готово');progress2(100)}
async function back(){clearLines();status2('Обратная: загрузка 5×5 метеосетки…');progress2(3);const base={lat:+blat.value,lon:+blon.value,alt:+balt.value,duration:+bh.value,ascent:+bas.value,maxAlt:+balt.value,step:Math.max(1,+document.getElementById('bstep')?.value||1),time:new Date(btime.value)},n=Math.min(500,Math.max(1,+bm.value)),w=await wx(base.lat,base.lon,Math.max(8,base.duration*25),new Date(base.time.getTime()-base.duration*3600000-3600000),base.time),all=[];for(let i=0;i<n;i++){const p={...base,alt:Math.max(1,base.alt+gauss()*50),time:new Date(base.time.getTime()+gauss()*60000),ascent:Math.max(.1,base.ascent+gauss()*.7)};const q=integrate(w,p,true);if(q.length)all.push(q);if(i%2===0){progress2(5+90*(i+1)/n);await sleep()}}if(!all.length)throw Error('Не построена ни одна обратная траектория');all.forEach((p,i)=>line(p,i?'#d9c8e8':'#8a2be2',i?1:3));fitAll();const ends=all.map(x=>x.at(-1)),la=ends.reduce((s,p)=>s+p.lat,0)/ends.length,lo=ends.reduce((s,p)=>s+p.lon,0)/ends.length;showResult('<b>Оценка запуска:</b> '+la.toFixed(5)+', '+lo.toFixed(5)+'<br><b>Валидных траекторий:</b> '+all.length+'/'+n+'<br><b>Модель:</b> 5×5 · pressure levels · RK4 · browser');status2('Готово');progress2(100)}
async function favorable(){if(typeof window.favorableExact==='function')return window.favorableExact();throw Error('Планировщик favorable пока не экспортирован из engine-favorable.js')}
window.weterBrowserRuntime={direct,back,favorable};window.runTrajectoryBrowser=direct;window.runBackBrowser=back;window.runFavorableBrowser=favorable;
window.direct=direct;window.back=back;window.fav=favorable;
})();