/* Weter browser engine: closer numerical port of the Python backtrajectory.py + trajectory.py. */
(()=>{
'use strict';
const EARTH=6371000,G=9.80665,RD=287.05;
const LEVELS=[1000,975,950,925,900,850,800,700,600,500,400,300,250,200];
const rad=x=>x*Math.PI/180,deg=x=>x*180/Math.PI,cl=(x,a,b)=>Math.max(a,Math.min(b,x));
const sleep=()=>new Promise(r=>setTimeout(r,0));
function move(lat,lon,e,n){const lr=rad(lat);return[cl(lat+deg(n/EARTH),-89.999999,89.999999),((lon+deg(e/(EARTH*Math.max(Math.cos(lr),1e-8)))+180)%360)-180]}
function distance(a,b){const p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lon-a.lon),h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*EARTH*Math.asin(Math.sqrt(cl(h,0,1)))}
function uv(s,d){const a=rad((d+180)%360);return[s*Math.sin(a),s*Math.cos(a)]}
function wind(s,n){const sp=Math.hypot(s,n);if(sp<1e-6)return[0,0];return[sp,(deg(Math.atan2(s,n))+540)%360]}
function grid(lat,lon,margin){const xs=[-1,-.5,0,.5,1],ld=margin/111,od=margin/Math.max(20,111*Math.cos(rad(lat)));return{lats:xs.map(x=>lat+x*ld),lons:xs.map(x=>lon+x*od)}}
function variables(){return LEVELS.flatMap(p=>['wind_speed_'+p+'hPa','wind_direction_'+p+'hPa','temperature_'+p+'hPa','geopotential_height_'+p+'hPa']).join(',')}
async function weather(lat,lon,radiusKm,start,end){const g=grid(lat,lon,radiusKm),age=(Date.now()-start.getTime())/86400000;let url,params;if(age>5.5){url='https://archive-api.open-meteo.com/v1/archive';params={start_date:start.toISOString().slice(0,10),end_date:end.toISOString().slice(0,10)}}else{url='https://api.open-meteo.com/v1/forecast';params={past_days:Math.min(92,Math.max(1,Math.floor(Math.max(0,age))+3)),forecast_days:2}}Object.assign(params,{latitude:g.lats.join(','),longitude:g.lons.join(','),hourly:variables(),timezone:'UTC',wind_speed_unit:'ms',temperature_unit:'celsius'});const r=await fetch(url+'?'+new URLSearchParams(params));if(!r.ok)throw Error('Open-Meteo HTTP '+r.status);let cells=await r.json();if(!Array.isArray(cells))cells=[cells];if(!cells.length)throw Error('Open-Meteo вернул пустой ответ');return{cells,lats:g.lats,lons:g.lons,times:cells[0].hourly.time.map(x=>new Date(x+'Z'))}}
function tb(ts,t){if(t<=ts[0])return[0,0,0];if(t>=ts.at(-1)){let n=ts.length-1;return[n,n,0]}let l=0,h=ts.length-1;while(l<h){let m=(l+h)>>1;if(ts[m]<t)l=m+1;else h=m}let i1=l,i0=i1-1;return[i0,i1,(t-ts[i0])/(ts[i1]-ts[i0])]}
function nb(w,c,z,t){const h=c.hourly,[i,j,f]=tb(w.times,t),v=[];for(const p of LEVELS){const s=h['wind_speed_'+p+'hPa'],d=h['wind_direction_'+p+'hPa'],T=h['temperature_'+p+'hPa'],g=h['geopotential_height_'+p+'hPa'];if(!s||!d||!T||!g||s[i]==null||s[j]==null||g[i]==null||g[j]==null)continue;const [u0,n0]=uv(+s[i],+d[i]),[u1,n1]=uv(+s[j],+d[j]);v.push([+g[i]+(+g[j]-+g[i])*f,u0+(u1-u0)*f,n0+(n1-n0)*f,+T[i]+(+T[j]-+T[i])*f+273.15,p*100])}v.sort((a,b)=>a[0]-b[0]);if(!v.length)throw Error('Нет данных ветра для выбранного времени/места');if(z<=v[0][0])return v[0].slice(1);if(z>=v.at(-1)[0])return v.at(-1).slice(1);for(let k=1;k<v.length;k++)if(z<=v[k][0]){let q=(z-v[k-1][0])/(v[k][0]-v[k-1][0]);return[v[k-1][1]+(v[k][1]-v[k-1][1])*q,v[k-1][2]+(v[k][2]-v[k-1][2])*q,v[k-1][3]+(v[k][3]-v[k-1][3])*q,Math.exp(Math.log(v[k-1][4])+(Math.log(v[k][4])-Math.log(v[k-1][4]))*q)]}}
function state(w,lat,lon,z,t){const bx=(a,x)=>{if(x<=a[0])return[0,0,0];if(x>=a.at(-1)){let n=a.length-1;return[n,n,0]}let i=1;while(a[i]<x)i++;return[i-1,i,(x-a[i-1])/(a[i]-a[i-1])]},[y0,y1,fy]=bx(w.lats,lat),[x0,x1,fx]=bx(w.lons,lon),at=(y,x)=>w.cells[y*5+x]||w.cells[0],a=nb(w,at(y0,x0),z,t),b=nb(w,at(y0,x1),z,t),c=nb(w,at(y1,x0),z,t),d=nb(w,at(y1,x1),z,t),bl=k=>k[0]*(1-fx)*(1-fy)+k[1]*fx*(1-fy)+k[2]*(1-fx)*fy+k[3]*fx*fy;return[bl([a[0],b[0],c[0],d[0]]),bl([a[1],b[1],c[1],d[1]]),bl([a[2],b[2],c[2],d[2]]),bl([a[3],b[3],c[3],d[3]]),bl([a[4],b[4],c[4],d[4]])]}
function gaussian(r){let u=Math.max(1e-12,r()),v=Math.max(1e-12,r());return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function rng(seed){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function perturbed(w,seed,sigma=1.5){const r=rng(seed),cells=w.cells.map(c=>{const o={...c,hourly:{...c.hourly}};for(const p of LEVELS){const sk='wind_speed_'+p+'hPa',dk='wind_direction_'+p+'hPa',ss=o.hourly[sk],dd=o.hourly[dk];if(!ss||!dd)continue;const s=[...ss],d=[...dd];let ce=0,cn=0,se=0,sn=0;for(let i=0;i<s.length;i++){if(s[i]==null||d[i]==null)continue;const q=sigma*(1+.35*Math.sqrt(Math.max(0,i)/24));ce=.82*ce+gaussian(r)*q*.30;cn=.82*cn+gaussian(r)*q*.30;se=.88*se+gaussian(r)*q*.55;sn=.88*sn+gaussian(r)*q*.55;const [u,v]=uv(+s[i],+d[i]),uu=u+ce+se,vv=v+cn+sn;s[i]=Math.hypot(uu,vv);d[i]=(deg(Math.atan2(uu,vv))+540)%360}o.hourly[sk]=s;o.hourly[dk]=d}return o});return{...w,cells}}
function trajectory(w,p,bias=[0,0]){let lat=p.lat,lon=p.lon,z=p.alt,t=new Date(p.time),elapsed=0,total=p.duration*3600,dt0=p.step*60,out=[];const deriv=(la,lo,zz,tt)=>{const s=state(w,la,lo,zz,tt);return[s[0]+bias[0],s[1]+bias[1],zz>=p.maxAlt?0:p.ascent]};const add=()=>{const [u,v]=deriv(lat,lon,z,t);out.push({time:t.toISOString(),lat,lon,altitude_m:z,u_mps:u,v_mps:v,wind_speed_mps:Math.hypot(u,v)})};add();while(elapsed<total-1e-9){const dt=Math.min(dt0,total-elapsed),k1=deriv(lat,lon,z,t),p2=move(lat,lon,k1[0]*dt/2,k1[1]*dt/2),t2=new Date(t-dt*0.0+dt*500),z2=Math.min(p.maxAlt,z+k1[2]*dt/2),k2=deriv(p2[0],p2[1],z2,t2),p3=move(lat,lon,k2[0]*dt/2,k2[1]*dt/2),z3=Math.min(p.maxAlt,z+k2[2]*dt/2),k3=deriv(p3[0],p3[1],z3,t2),p4=move(lat,lon,k3[0]*dt,k3[1]*dt),z4=Math.min(p.maxAlt,z+k3[2]*dt),t4=new Date(t.getTime()+dt*1000),k4=deriv(p4[0],p4[1],z4,t4);[lat,lon]=move(lat,lon,dt*(k1[0]+2*k2[0]+2*k3[0]+k4[0])/6,dt*(k1[1]+2*k2[1]+2*k3[1]+k4[1])/6);z=Math.min(p.maxAlt,z+dt*(k1[2]+2*k2[2]+2*k3[2]+k4[2])/6);t=t4;elapsed+=dt;add()}return out}
function back(w,det,ascent,step,bias,r){let lat=det.lat,lon=det.lon,z=det.alt,t=new Date(det.time),elapsed=0,total=det.duration*3600,out=[];const rate=(zz,s)=>{const rho=s[4]/(RD*Math.max(s[3],150));const base=ascent*(.65+.35*Math.min(Math.sqrt(1.225/Math.max(rho,.05)),1.8));return Math.max(.5,base+gaussian(r)*.7)};const deriv=(la,lo,zz,tt)=>{const s=state(w,la,lo,zz,tt),a=rate(zz,s);return[-s[0]-bias[0],-s[1]-bias[1],-a,s]};while(elapsed<total&&z>10){const dt=Math.min(step,total-elapsed),k1=deriv(lat,lon,z,t),p2=move(lat,lon,k1[0]*dt/2,k1[1]*dt/2),z2=Math.max(1,z+k1[2]*dt/2),t2=new Date(t.getTime()-dt*500),k2=deriv(p2[0],p2[1],z2,t2),p3=move(lat,lon,k2[0]*dt/2,k2[1]*dt/2),z3=Math.max(1,z+k2[2]*dt/2),k3=deriv(p3[0],p3[1],z3,t2),p4=move(lat,lon,k3[0]*dt,k3[1]*dt),z4=Math.max(1,z+k3[2]*dt),t4=new Date(t.getTime()-dt*1000),k4=deriv(p4[0],p4[1],z4,t4);let east=dt*(k1[0]+2*k2[0]+2*k3[0]+k4[0])/6,north=dt*(k1[1]+2*k2[1]+2*k3[1]+k4[1])/6,vertical=dt*(k1[2]+2*k2[2]+2*k3[2]+k4[2])/6;if(z+vertical<=0){const f=z/Math.max(z-vertical,1e-9);east*=f;north*=f;vertical=-z;elapsed+=dt*f;t=new Date(t.getTime()-dt*f*1000)}else{elapsed+=dt;t=t4}[lat,lon]=move(lat,lon,east,north);z=Math.max(0,z+vertical);out.push({time:t.toISOString(),lat,lon,altitude_m:z,u_mps:k1[0],v_mps:k1[1],wind_speed_mps:Math.hypot(k1[0],k1[1])});if(z<=10)break}return out}
function quantile(points,q){if(!points.length)return 0;const lat0=rad(points.reduce((s,p)=>s+p.lat,0)/points.length),lon0=points.reduce((s,p)=>s+p.lon,0)/points.length;const ds=points.map(p=>Math.hypot((rad(p.lon)-rad(lon0))*EARTH*Math.cos(lat0),(rad(p.lat)-rad(points.reduce((s,x)=>s+x.lat,0)/points.length))*EARTH)).sort((a,b)=>a-b),x=(ds.length-1)*q,l=Math.floor(x),f=x-l;return ds[l]+(ds[l+1]??ds[l])*f}
function uiStatus(s,e=false){if(typeof status==='function')status(s,e);else{const x=document.getElementById('status');if(x){x.textContent=s;x.style.color=e?'#c00':''}}}
function uiProgress(v,show=true){if(typeof progress==='function')progress(v,show)}
function clear(){if(typeof clearLines==='function')clearLines()}
function draw(pts,color,w=2){if(typeof line==='function')line(pts,color,w)}
async function runBackExact(){clear();try{const det={lat:+blat.value,lon:+blon.value,alt:+balt.value,time:new Date(btime.value),duration:Math.min(48,Math.max(.01,+bh.value))},members=Math.max(1,Math.min(1000,+bm.value)),step=Math.max(1,+document.getElementById('bstep')?.value||1);uiStatus('Загрузка 5×5 метеосетки…');uiProgress(3);const w=await weather(det.lat,det.lon,Math.max(6,det.duration*1.8),new Date(det.time-det.duration*3600000-10800000),det.time);const launches=[],trajs=[];for(let i=0;i<members;i++){const r=rng(42+i),tm=new Date(det.time.getTime()+gaussian(r)*60000),z=Math.max(1,det.alt+gaussian(r)*50),bw=[gaussian(r)*1.5,gaussian(r)*1.5];try{const pts=back(w,{...det,time:tm,alt:z},Math.max(.01,+bas.value),step*60,bw,r);if(pts.length){trajs.push(pts);launches.push(pts.at(-1))}}catch(e){}if(i%2===0){uiProgress(5+85*(i+1)/members);await sleep()}}if(!launches.length)throw Error('Не удалось построить ни одной обратной траектории');const clat=launches.reduce((s,p)=>s+p.lat,0)/launches.length,clon=launches.reduce((s,p)=>s+p.lon,0)/launches.length,center={lat:clat,lon:clon},zones=[.5,.8,.95].map(q=>({probability:q,radius_m:quantile(launches,q),center_lat:clat,center_lon:clon})),best=launches[launches.map(p=>distance(p,center)).indexOf(Math.min(...launches.map(p=>distance(p,center))))];trajs.forEach((p,i)=>draw(p,i===0?'#b8a2d9':'#d9c8e8',1));draw(trajs[0]||[],'#8a2be2',3);if(typeof fitAll==='function')fitAll();showResult('<b>Оценка запуска:</b> '+best.lat.toFixed(5)+', '+best.lon.toFixed(5)+'<br><b>Время:</b> '+best.time+'<br><b>Ансамбль:</b> '+launches.length+'/'+members+'<div class="chips">'+zones.map(x=>'<span class="chip">'+Math.round(x.probability*100)+'%: '+Math.round(x.radius_m)+' м</span>').join('')+'</div>');uiStatus('Готово');uiProgress(100);setTimeout(()=>uiProgress(0,false),500)}catch(e){uiProgress(0,false);uiStatus(e.message,true)}}
async function runDirectExact(){clear();try{const p={lat:+dlat.value,lon:+dlon.value,alt:+dalt.value,ascent:+das.value,maxAlt:+dmax.value,duration:+dh.value,step:5,time:new Date(dtime.value)};if(p.alt<0||p.maxAlt<0||p.alt>p.maxAlt||p.duration<=0||p.step<=0||p.ascent<0)throw Error('Проверьте параметры траектории');uiStatus('Загрузка 5×5 метеосетки…');uiProgress(3);const w=await weather(p.lat,p.lon,Math.max(6,p.duration*1.8),p.time,new Date(p.time.getTime()+p.duration*3600000));const pts=trajectory(w,p);draw(pts);if(typeof fitAll==='function')fitAll();showResult('<b>Точек:</b> '+pts.length+'<br><b>Конец:</b> '+pts.at(-1).lat.toFixed(5)+', '+pts.at(-1).lon.toFixed(5)+'<br><b>Высота:</b> '+Math.round(pts.at(-1).altitude_m)+' м');uiStatus('Готово');uiProgress(100);setTimeout(()=>uiProgress(0,false),500)}catch(e){uiProgress(0,false);uiStatus(e.message,true)}}
window.back=runBackExact;window.direct=runDirectExact;
})();
