/* Weter browser computation engine.
 * Mirrors the Python application's numerical model as closely as practical:
 * 5x5 Open-Meteo pressure-level grid, time/vertical/bilinear interpolation,
 * RK4 forward/reverse integration, 150-member back ensemble, correlated wind
 * perturbations, target polygons, restricted/hazard zones and launch-window
 * screening. Calculations run in the browser to avoid PHP shared-host limits.
 */
(() => {
'use strict';
const OM_FORECAST='https://api.open-meteo.com/v1/forecast';
const OM_ARCHIVE='https://archive-api.open-meteo.com/v1/archive';
const LEVELS=[1000,975,950,925,900,850,800,700,600,500,400,300,250,200];
const EARTH=6371000;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const rad=x=>x*Math.PI/180, deg=x=>x*180/Math.PI;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function utc(s){const d=new Date(s);if(isNaN(d))throw Error('Некорректная дата: '+s);return d;}
function iso(d){return new Date(d).toISOString();}
function move(lat,lon,east,north){const d=Math.hypot(east,north);if(d<1e-9)return[lat,lon];const b=Math.atan2(east,north),ad=d/EARTH,p=rad(lat),l=rad(lon);const p2=Math.asin(Math.sin(p)*Math.cos(ad)+Math.cos(p)*Math.sin(ad)*Math.cos(b));const l2=l+Math.atan2(Math.sin(b)*Math.sin(ad)*Math.cos(p),Math.cos(ad)-Math.sin(p)*Math.sin(p2));return[deg(p2),((deg(l2)+540)%360)-180];}
function dist(a,b,c,d){const p1=rad(a),p2=rad(c),dp=rad(c-a),dl=rad(d-b);const h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*EARTH*Math.asin(Math.sqrt(clamp(h,0,1)));}
function wuv(speed,from){const a=rad((from+180)%360);return[speed*Math.sin(a),speed*Math.cos(a)];}
function uvw(u,v){const s=Math.hypot(u,v);if(s<1e-9)return[0,0];return[s,(deg(Math.atan2(u,v))+180+360)%360];}
function rng(seed){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296;};}
function gaussian(r){let u=Math.max(1e-12,r()),v=Math.max(1e-12,r());return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);}
function radius(h){return Math.min(8000,Math.max(600,600+h*44));}
function grid(lat,lon,rkm){const ld=rkm/111,od=rkm/Math.max(20,111*Math.cos(rad(lat))), xs=[-1,-.5,0,.5,1];return {lats:xs.map(x=>lat+ld*x),lons:xs.map(x=>lon+od*x)};}
function vars(){const a=[];for(const p of LEVELS){a.push(`wind_speed_${p}hPa`,`wind_direction_${p}hPa`,`temperature_${p}hPa`,`geopotential_height_${p}hPa`);}a.push('precipitation','weather_code');return a.join(',');}
async function fetchWeather(centerLat,centerLon,rkm,start,end){
 const g=grid(centerLat,centerLon,rkm);const lat=g.lats.join(',');const lon=g.lons.join(',');
 const now=Date.now(), age=(now-start.getTime())/86400000;let url,params;
 if(age>5.5){url=OM_ARCHIVE;params={latitude:lat,longitude:lon,hourly:vars(),start_date:start.toISOString().slice(0,10),end_date:end.toISOString().slice(0,10),timezone:'UTC',wind_speed_unit:'ms',temperature_unit:'celsius'};}
 else {url=OM_FORECAST;const past=Math.min(92,Math.max(1,Math.floor(Math.max(0,age))+3));params={latitude:lat,longitude:lon,hourly:vars(),past_days:past,forecast_days:2,timezone:'UTC',wind_speed_unit:'ms',temperature_unit:'celsius'};}
 const q=new URLSearchParams(params);const res=await fetch(url+'?'+q.toString());if(!res.ok)throw Error('Open-Meteo HTTP '+res.status);let data=await res.json();if(!Array.isArray(data))data=[data];if(!data.length)throw Error('Open-Meteo вернул пустой ответ');
 return {cells:data,lats:g.lats,lons:g.lons,times:data[0].hourly.time.map(t=>new Date(t+'Z'))};
}
function bracket(xs,x){if(x<=xs[0])return[0,0,0];if(x>=xs[xs.length-1])return[xs.length-1,xs.length-1,0];let hi=1;while(hi<xs.length&&xs[hi]<x)hi++;let lo=hi-1;return[lo,hi,(x-xs[lo])/(xs[hi]-xs[lo])];}
function timeBracket(times,t){if(t<=times[0])return[0,0,0];if(t>=times[times.length-1]){const n=times.length-1;return[n,n,0];}let lo=0,hi=times.length-1;while(lo<hi){const m=(lo+hi)>>1;if(times[m]<t)lo=m+1;else hi=m;}const i1=lo,i0=i1-1;return[i0,i1,(t-times[i0])/(times[i1]-times[i0])];}
function nodeState(w,cell,alt,t){const h=cell.hourly,[i0,i1,f]=timeBracket(w.times,t),v=[];for(const p of LEVELS){const s0=h[`wind_speed_${p}hPa`],s1=s0,d0=h[`wind_direction_${p}hPa`],z0=h[`geopotential_height_${p}hPa`],tm=h[`temperature_${p}hPa`];if(!s0||!d0||!z0||!tm||s0[i0]==null||s0[i1]==null)continue;let sp0=+s0[i0],sp1=+s0[i1],di0=+d0[i0],di1=+d0[i1];let [u0,n0]=wuv(sp0,di0),[u1,n1]=wuv(sp1,di1);let z=+z0[i0]+(+z0[i1]-+z0[i0])*f;let T=(+tm[i0]+(+tm[i1]-+tm[i0])*f)+273.15;v.push([z,u0+(u1-u0)*f,n0+(n1-n0)*f,T,p*100]);}
 if(!v.length)throw Error('Для выбранного времени нет вертикального профиля ветра');v.sort((a,b)=>a[0]-b[0]);if(alt<=v[0][0])return v[0].slice(1);let k=v.length-1;if(alt>=v[k][0])return v[k].slice(1);for(let i=1;i<v.length;i++)if(alt<=v[i][0]){const f2=(alt-v[i-1][0])/Math.max(.001,v[i][0]-v[i-1][0]);return[v[i-1][1]+(v[i][1]-v[i-1][1])*f2,v[i-1][2]+(v[i][2]-v[i-1][2])*f2,v[i-1][3]+(v[i][3]-v[i-1][3])*f2,v[i-1][4]+(v[i][4]-v[i-1][4])*f2];}return v[k].slice(1);}
function state(w,lat,lon,alt,t){const [iy0,iy1,fy]=bracket(w.lats,lat),[ix0,ix1,fx]=bracket(w.lons,lon);const cells=w.cells;function at(iy,ix){return cells[iy*5+ix]||cells[0];}const s00=nodeState(w,at(iy0,ix0),alt,t),s01=nodeState(w,at(iy0,ix1),alt,t),s10=nodeState(w,at(iy1,ix0),alt,t),s11=nodeState(w,at(iy1,ix1),alt,t);const blend=(a,b,c,d)=>a*(1-fx)*(1-fy)+b*fx*(1-fy)+c*(1-fx)*fy+d*fx*fy;return[blend(s00[0],s01[0],s10[0],s11[0]),blend(s00[1],s01[1],s10[1],s11[1]),blend(s00[2],s01[2],s10[2],s11[2]),blend(s00[3],s01[3],s10[3],s11[3])];}
function wind(w,lat,lon,alt,t,bias=[0,0]){const s=state(w,lat,lon,alt,t);return[s[0]+bias[0],s[1]+bias[1]];}
function trajectory(w,p){let lat=p.lat,lon=p.lon,z=p.startAltitude,t=new Date(p.startTime),elapsed=0,total=p.durationHours*3600,dt0=p.stepMinutes*60,pts=[];const push=()=>{const [u,v]=wind(w,lat,lon,z,t);const [speed,dir]=uvw(u,v);pts.push({time:iso(t),lat,lon,altitude_m:z,u_mps:u,v_mps:v,wind_speed_mps:speed,wind_direction:dir});};push();while(elapsed<total-1e-9){const dt=Math.min(dt0,total-elapsed),k=(la,lo,zz,tt)=>{const [u,v]=wind(w,la,lo,zz,tt);return[u,v,zz>=p.maxAltitude?0:p.ascentRate];};const [u1,v1,z1]=k(lat,lon,z,t);let [la2,lo2]=move(lat,lon,u1*dt/2,v1*dt/2),z2=Math.min(p.maxAltitude,z+z1*dt/2),t2=new Date(t.getTime()+dt*500);const [u2,v2,zv2]=k(la2,lo2,z2,t2);[la2,lo2]=move(lat,lon,u2*dt/2,v2*dt/2);z2=Math.min(p.maxAltitude,z+zv2*dt/2);const [u3,v3,zv3]=k(la2,lo2,z2,t2);let [la4,lo4]=move(lat,lon,u3*dt,v3*dt),z4=Math.min(p.maxAltitude,z+zv3*dt),t4=new Date(t.getTime()+dt*1000);const [u4,v4,zv4]=k(la4,lo4,z4,t4);const e=dt/6*(u1+2*u2+2*u3+u4),n=dt/6*(v1+2*v2+2*v3+v4),vz=dt/6*(z1+2*zv2+2*zv3+zv4);[lat,lon]=move(lat,lon,e,n);z=Math.min(p.maxAltitude,z+vz);t=new Date(t.getTime()+dt*1000);elapsed+=dt;push();}returnpts;}
function percentile(a,p){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),i=(b.length-1)*p,l=Math.floor(i),f=i-l;return b[l]+(b[l+1]??b[l]-b[l])*f;}
function backTrajectory(w,duration,det,alt,ascent,step,bias){let lat=det.lat,lon=det.lon,z=Math.max(0,alt),t=new Date(det.time),remaining=duration*3600,elapsed=0,pts=[];const maxAlt=Math.max(10000,z),onPlateau=z>=.95*maxAlt,ascentTime=onPlateau?Math.max(0,(maxAlt)/Math.max(.01,ascent)):0,plateau=Math.max(0,remaining-ascentTime);const vr=()=>{if(z<=1e-6)return 0;if(onPlateau&&elapsed<plateau)return 0;return ascent;};const push=()=>{const [u,v]=wind(w,lat,lon,z,t,bias),[sp,di]=uvw(u,v);pts.push({time:iso(t),lat,lon,altitude_m:z,u_mps:u,v_mps:v,wind_speed_mps:sp,wind_direction:di});};push();while(remaining>1e-9&&z>1e-6){const h=Math.min(step,remaining),dt=-h;let [u1,v1]=wind(w,lat,lon,z,t,bias),z1=vr();let [la2,lo2]=move(lat,lon,u1*dt/2,v1*dt/2),zz2=Math.max(0,z+z1*dt/2),tt2=new Date(t.getTime()+dt*500);let [u2,v2]=wind(w,la2,lo2,zz2,tt2,bias),z2=(!onPlateau||elapsed+h/2>=plateau)?ascent:0;[la2,lo2]=move(lat,lon,u2*dt/2,v2*dt/2);zz2=Math.max(0,z+z2*dt/2);let [u3,v3]=wind(w,la2,lo2,zz2,tt2,bias),z3=(!onPlateau||elapsed+h/2>=plateau)?ascent:0;let [la4,lo4]=move(lat,lon,u3*dt,v3*dt),zz4=Math.max(0,z+z3*dt),tt4=new Date(t.getTime()+dt*1000);let [u4,v4]=wind(w,la4,lo4,zz4,tt4,bias),z4=(!onPlateau||elapsed+h>=plateau)?ascent:0;[lat,lon]=move(lat,lon,dt/6*(u1+2*u2+2*u3+u4),dt/6*(v1+2*v2+2*v3+v4));z=Math.max(0,z+dt/6*(z1+2*z2+2*z3+z4));t=new Date(t.getTime()+dt*1000);elapsed+=h;remaining-=h;push();}return pts;}
function correlatedPerturb(base,seed,sigma){const r=rng(seed),cells=base.cells.map(c=>({latitude:c.latitude,longitude:c.longitude,hourly:{...c.hourly}}));for(const c of cells){let ce=0,cn=0,se=0,sn=0;for(const p of LEVELS){const sk=`wind_speed_${p}hPa`,dk=`wind_direction_${p}hPa`,sp=c.hourly[sk],dr=c.hourly[dk];if(!sp||!dr)continue;const ns=[...sp],nd=[...dr];for(let i=0;i<ns.length;i++){if(ns[i]==null||dr[i]==null)continue;const sg=sigma*(1+.35*Math.sqrt(Math.max(0,i)/24));ce=.82*ce+gaussian(r)*sg*.30;cn=.82*cn+gaussian(r)*sg*.30;se=.88*se+gaussian(r)*sg*.55;sn=.88*sn+gaussian(r)*sg*.55;const [u,v]=wuv(+ns[i],+dr[i]);const uu=u+ce+se,vv=v+cn+sn;ns[i]=Math.hypot(uu,vv);nd[i]=(deg(Math.atan2(uu,vv))+180+360)%360;}c.hourly[sk]=ns;c.hourly[dk]=nd;}}return{...base,cells};}
async function runBack(){clearLines();try{const det={lat:+blat.value,lon:+blon.value,time:new Date(btime.value).toISOString()},hours=Math.min(48,Math.max(.05,+bh.value)),members=Math.max(20,Math.min(500,+bm.value)),step=Math.max(1,+document.getElementById('bstep')?.value||1);status('Загрузка пространственного прогноза…');progress(5);const w=await fetchWeather(det.lat,det.lon,Math.max(600,radius(hours)),new Date(new Date(det.time).getTime()-hours*3600000),new Date(det.time));const trajectories=[],launch=[];for(let i=0;i<members;i++){const r=rng(42+i*7919),tm=new Date(new Date(det.time).getTime()+gaussian(r)*60000),z=Math.max(0,+balt.value+gaussian(r)*50),as=Math.max(.2,gaussian(r)*.7+(+bas.value||5)),du=gaussian(r)*1.5,dv=gaussian(r)*1.5;try{const pts=backTrajectory(w,hours,{lat:det.lat,lon:det.lon,time:tm},z,as,step*60,[du,dv]);if(pts.length){trajectories.push(pts);const q=pts.at(-1);launch.push(q);}}catch(e){}if(i%2===0){progress(5+85*(i+1)/members);await sleep(0);}}if(!launch.length)throw Error('Не удалось построить ни одной обратной траектории');const clat=launch.reduce((s,p)=>s+p.lat,0)/launch.length,clon=launch.reduce((s,p)=>s+p.lon,0)/launch.length,ds=launch.map(p=>dist(clat,clon,p.lat,p.lon)),zones=[.5,.8,.95].map(p=>({probability:p,radius_m:percentile(ds,p),center_lat:clat,center_lon:clon})),bi=ds.indexOf(Math.min(...ds)),best=launch[bi];clearLines();trajectories.forEach((p,i)=>line(p,i===bi?'#8a2be2':'#b8a2d9',i===bi?3:1));fitAll();showResult('<b>Оценка запуска:</b> '+best.lat.toFixed(5)+', '+best.lon.toFixed(5)+'<br><b>Ансамбль:</b> '+launch.length+'/'+members+'<div class="chips">'+zones.map(x=>'<span class="chip">'+Math.round(x.probability*100)+'%: '+Math.round(x.radius_m)+' м</span>').join('')+'</div>');status('Готово');progress(100);setTimeout(()=>progress(0,false),500);}catch(e){progress(0,false);status(e.message,true);}}
function pointInPoly(p,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a.lon>p.lon)!=(b.lon>p.lon)&&p.lat<(b.lat-a.lat)*(p.lon-a.lon)/(b.lon-a.lon)+a.lat)inside=!inside;}return inside;}
function segIntersect(a,b,c,d){const o=(p,q,r)=>(q.lon-p.lon)*(r.lat-p.lat)-(q.lat-p.lat)*(r.lon-p.lon);const o1=o(a,b,c),o2=o(a,b,d),o3=o(c,d,a),o4=o(c,d,b);return((o1>0)!=(o2>0))&&((o3>0)!=(o4>0));}
function trajectoryHitsPoly(pts,poly){if(!poly||poly.length<3)return false;for(const p of pts)if(pointInPoly(p,poly))return true;for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i];for(let j=0;j<poly.length;j++)if(segIntersect(a,b,poly[j],poly[(j+1)%poly.length]))return true;}return false;}
function targetHit(pts,target,radiusM,poly){let min=Infinity,best=pts[0],inside=0;for(const p of pts){const d=poly?.length>=3?(pointInPoly(p,poly)?0:Infinity):dist(p.lat,p.lon,target.lat,target.lon);if(d<min){min=d;best=p;}if(poly?.length>=3?pointInPoly(p,poly):dist(p.lat,p.lon,target.lat,target.lon)<=radiusM)inside++;}return{min,best,inside,hit:poly?.length>=3?trajectoryHitsPoly(pts,poly):min<=radiusM};}
function launchPoints(c,r,rings=2,per=12){const out=[c];for(let ring=1;ring<=rings;ring++){const rr=r*ring/rings,count=Math.max(8,per*ring);for(let i=0;i<count;i++){const a=2*Math.PI*i/count;out.push({lat:c.lat+rr*Math.cos(a)/111320,lon:c.lon+rr*Math.sin(a)/(111320*Math.max(.15,Math.cos(rad(c.lat))))});}}return out;}
function surfaceShear(w,p,t,top){const [u1,v1]=wind(w,p.lat,p.lon,10,t),[u2,v2]=wind(w,p.lat,p.lon,Math.max(100,top),t);return[Math.hypot(u1,v1),Math.hypot(u2-u1,v2-v1)/Math.max(1,top-10)];}
function hazard(w,pts,limit){for(const p of pts){const cell=w.cells.reduce((a,c)=>((+c.latitude-p.lat)**2+(+c.longitude-p.lon)**2)<((+a.latitude-p.lat)**2+(+a.longitude-p.lon)**2)?c:a);const ts=cell.hourly.time,idx=ts.reduce((bi,x,i)=>Math.abs(new Date(x+'Z')-new Date(p.time))<Math.abs(new Date(ts[bi]+'Z')-new Date(p.time))?i:bi,0);const code=cell.hourly.weather_code?.[idx],rain=cell.hourly.precipitation?.[idx]??0;if([95,96,99].includes(+code)||+rain>limit)return true;}return false;}
async function runFav(){clearLines();try{const target={lat:+tlat.value,lon:+tlon.value},center={lat:+clat.value,lon:+clon.value},start=new Date(fs.value),end=new Date(fe.value),lh=Math.max(.1,+fh.value),launchR=Math.max(100,+fr.value),targetR=Math.max(100,+ftr.value),stepH=Math.max(.25,+fts.value),rings=2,per=12,ens=Math.max(5,Math.min(150,+fens.value)),maxAlt=+fmax.value,as=+fas.value;status('Загрузка пространственного прогноза…');progress(3);const w=await fetchWeather((target.lat+center.lat)/2,(target.lon+center.lon)/2,Math.max(600,radius(lh)+launchR/1000),start,new Date(end.getTime()+lh*3600000));const candidates=[];const points=launchPoints(center,launchR,rings,per);let total=Math.max(1,Math.ceil((end-start)/3600000/stepH))*points.length,done=0;for(let t=start.getTime();t<=end.getTime();t+=stepH*3600000){for(const lp of points){const [sw,sh]=surfaceShear(w,lp,new Date(t),maxAlt);if(sw>+fwind.value||sh>+fshear.value){done++;continue;}const pts=trajectory(w,{lat:lp.lat,lon:lp.lon,startAltitude:0,ascentRate:as,maxAltitude:maxAlt,durationHours:lh,stepMinutes:2,startTime:new Date(t)}),q=targetHit(pts,target,targetR,null);if(q.hit&&!hazard(w,pts,+frain.value))candidates.push({launch_time:iso(new Date(t)),launch_point:lp,trajectory:pts,min_distance_to_target_m:q.min,time_in_target_s:q.inside*120,surface_wind_mps:sw,shear_s_inv:sh});done++;progress(3+35*done/total);await sleep(0);}}
 // Ensemble refinement of every surviving candidate, matching the main application's uncertainty model.
 for(let ci=0;ci<candidates.length;ci++){const c=candidates[ci],results=[];for(let m=0;m<ens;m++){const pw=correlatedPerturb(w,1009*m+ci,1.5),pts=trajectory(pw,{lat:c.launch_point.lat,lon:c.launch_point.lon,startAltitude:0,ascentRate:as,maxAltitude:maxAlt,durationHours:lh,stepMinutes:2,startTime:new Date(c.launch_time)}),q=targetHit(pts,target,targetR,null);if(q.hit&&!hazard(pw,pts,+frain.value))results.push(q.min);}c.ensemble_success_rate=results.length/ens;c.ensemble_median_distance_m=percentile(results,.5);c.ensemble_p90_distance_m=percentile(results,.9);c.score=(c.ensemble_median_distance_m||1e9)/Math.max(100,targetR)-Math.min(c.time_in_target_s/3600,2)*.15+(c.surface_wind_mps/+fwind.value)*.05+(c.shear_s_inv/+fshear.value)*.05;progress(40+55*(ci+1)/Math.max(1,candidates.length));await sleep(0);}
candidates.sort((a,b)=>a.score-b.score);const windows=candidates.slice(0,20).map(c=>({...c,filters:{surface_wind:true,shear:true}}));clearLines();windows.forEach((w,i)=>line(w.trajectory,i===0?'#e53935':'#ff8a80',i===0?4:2));fitAll();let html='<b>Найдено кандидатов:</b> '+candidates.length;if(windows.length)html+='<br><b>Рекомендуемое:</b> '+new Date(windows[0].launch_time).toLocaleString()+'<br><br>'+windows.map((w,i)=>'<div class="window"><b>'+(i+1)+'. '+new Date(w.launch_time).toLocaleString()+'</b><br>Старт: '+w.launch_point.lat.toFixed(5)+', '+w.launch_point.lon.toFixed(5)+'<br>До цели: '+(isFinite(w.min_distance_to_target_m)?Math.round(w.min_distance_to_target_m):'—')+' м<br>В цели: '+Math.round(w.time_in_target_s)+' с<br>Успех ансамбля: '+Math.round(w.ensemble_success_rate*100)+'%<br>Медиана: '+Math.round(w.ensemble_median_distance_m||0)+' м · P90: '+Math.round(w.ensemble_p90_distance_m||0)+' м<br>Ветер: '+w.surface_wind_mps.toFixed(2)+' м/с · сдвиг '+w.shear_s_inv.toExponential(2)+'</div>').join('');showResult(html);status('Готово');progress(100);setTimeout(()=>progress(0,false),500);}catch(e){progress(0,false);status(e.message,true);}}
async function runDirect(){clearLines();try{status('Загрузка пространственного прогноза…');progress(4);const p={lat:+dlat.value,lon:+dlon.value,startAltitude:+dalt.value,ascentRate:+das.value,maxAltitude:+dmax.value,durationHours:+dh.value,stepMinutes:5,startTime:new Date(dtime.value)};const w=await fetchWeather(p.lat,p.lon,radius(p.durationHours),new Date(p.startTime),new Date(p.startTime.getTime()+p.durationHours*3600000));const pts=trajectory(w,p);line(pts);fitAll();showResult('<b>Точек:</b> '+pts.length+'<br><b>Время:</b> '+new Date(pts[0].time).toLocaleString()+' → '+new Date(pts.at(-1).time).toLocaleString()+'<br><b>Конечная высота:</b> '+Math.round(pts.at(-1).altitude_m)+' м');status('Готово');progress(100);setTimeout(()=>progress(0,false),500);}catch(e){progress(0,false);status(e.message,true);}}
window.direct=runDirect;window.back=runBack;window.fav=runFav;
})();
