/* Weter browser computation engine.
 * Syntax-safe build: 5x5 Open-Meteo pressure-level grid, time/vertical/bilinear
 * interpolation, RK4 forward/reverse integration, ensemble backtracking and
 * favorable-window screening. Heavy calculations run in the browser.
 */
(() => {
'use strict';
const OM_FORECAST='https://api.open-meteo.com/v1/forecast';
const OM_ARCHIVE='https://archive-api.open-meteo.com/v1/archive';
const LEVELS=[1000,975,950,925,900,850,800,700,600,500,400,300,250,200];
const EARTH=6371000;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const rad=x=>x*Math.PI/180;
const deg=x=>x*180/Math.PI;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const iso=d=>new Date(d).toISOString();
function move(lat,lon,east,north){const d=Math.hypot(east,north);if(d<1e-9)return[lat,lon];const b=Math.atan2(east,north),ad=d/EARTH,p=rad(lat),l=rad(lon);const p2=Math.asin(Math.sin(p)*Math.cos(ad)+Math.cos(p)*Math.sin(ad)*Math.cos(b));const l2=l+Math.atan2(Math.sin(b)*Math.sin(ad)*Math.cos(p),Math.cos(ad)-Math.sin(p)*Math.sin(p2));return[deg(p2),((deg(l2)+540)%360)-180];}
function dist(a,b,c,d){const p1=rad(a),p2=rad(c),dp=rad(c-a),dl=rad(d-b);const h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*EARTH*Math.asin(Math.sqrt(clamp(h,0,1)));}
function wuv(speed,from){const a=rad((from+180)%360);return[speed*Math.sin(a),speed*Math.cos(a)];}
function uvw(u,v){const s=Math.hypot(u,v);if(s<1e-9)return[0,0];return[s,(deg(Math.atan2(u,v))+180+360)%360];}
function rng(seed){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296;};}
function gaussian(r){const u=Math.max(1e-12,r()),v=Math.max(1e-12,r());return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);}
function radius(h){return Math.min(8000,Math.max(600,600+h*44));}
function grid(lat,lon,rkm){const ld=rkm/111,od=rkm/Math.max(20,111*Math.cos(rad(lat))),xs=[-1,-.5,0,.5,1];return{lats:xs.map(x=>lat+ld*x),lons:xs.map(x=>lon+od*x)};}
function vars(){const a=[];for(const p of LEVELS){a.push('wind_speed_'+p+'hPa','wind_direction_'+p+'hPa','temperature_'+p+'hPa','geopotential_height_'+p+'hPa');}a.push('precipitation','weather_code');return a.join(',');}
async function fetchWeather(centerLat,centerLon,rkm,start,end){const g=grid(centerLat,centerLon,rkm);const params={latitude:g.lats.join(','),longitude:g.lons.join(','),hourly:vars(),timezone:'UTC',wind_speed_unit:'ms',temperature_unit:'celsius'};let url=OM_FORECAST;const age=(Date.now()-start.getTime())/86400000;if(age>5.5){url=OM_ARCHIVE;params.start_date=start.toISOString().slice(0,10);params.end_date=end.toISOString().slice(0,10);}else{params.past_days=Math.min(92,Math.max(1,Math.floor(Math.max(0,age))+3));params.forecast_days=2;}const res=await fetch(url+'?'+new URLSearchParams(params));if(!res.ok)throw Error('Open-Meteo HTTP '+res.status);let data=await res.json();if(!Array.isArray(data))data=[data];if(!data.length)throw Error('Open-Meteo вернул пустой ответ');return{cells:data,lats:g.lats,lons:g.lons,times:data[0].hourly.time.map(t=>new Date(t+'Z'))};}
function bracket(xs,x){if(x<=xs[0])return[0,0,0];if(x>=xs[xs.length-1]){const n=xs.length-1;return[n,n,0];}let hi=1;while(hi<xs.length&&xs[hi]<x)hi++;const lo=hi-1;return[lo,hi,(x-xs[lo])/(xs[hi]-xs[lo])];}
function timeBracket(times,t){if(t<=times[0])return[0,0,0];if(t>=times[times.length-1]){const n=times.length-1;return[n,n,0];}let lo=0,hi=times.length-1;while(lo<hi){const m=(lo+hi)>>1;if(times[m]<t)lo=m+1;else hi=m;}const i1=lo,i0=i1-1;return[i0,i1,(t-times[i0])/(times[i1]-times[i0])];}
function nodeState(w,cell,alt,t){const h=cell.hourly,[i0,i1,f]=timeBracket(w.times,t),v=[];for(const p of LEVELS){const s=h['wind_speed_'+p+'hPa'],d=h['wind_direction_'+p+'hPa'],z=h['geopotential_height_'+p+'hPa'];if(!s||!d||!z||s[i0]==null||s[i1]==null||z[i0]==null||z[i1]==null)continue;const[u0,n0]=wuv(+s[i0],+d[i0]),[u1,n1]=wuv(+s[i1],+d[i1]),zz=+z[i0]+(+z[i1]-+z[i0])*f;v.push([zz,u0+(u1-u0)*f,n0+(n1-n0)*f]);}if(!v.length)throw Error('Для выбранного времени нет вертикального профиля ветра');v.sort((a,b)=>a[0]-b[0]);if(alt<=v[0][0])return v[0].slice(1);if(alt>=v[v.length-1][0])return v[v.length-1].slice(1);for(let i=1;i<v.length;i++){if(alt<=v[i][0]){const q=(alt-v[i-1][0])/Math.max(.001,v[i][0]-v[i-1][0]);return[v[i-1][1]+(v[i][1]-v[i-1][1])*q,v[i-1][2]+(v[i][2]-v[i-1][2])*q];}}return v[v.length-1].slice(1);}
function state(w,lat,lon,alt,t){const[iy0,iy1,fy]=bracket(w.lats,lat),[ix0,ix1,fx]=bracket(w.lons,lon);const at=(y,x)=>w.cells[y*5+x]||w.cells[0];const a=nodeState(w,at(iy0,ix0),alt,t),b=nodeState(w,at(iy0,ix1),alt,t),c=nodeState(w,at(iy1,ix0),alt,t),d=nodeState(w,at(iy1,ix1),alt,t);const blend=(x,y,z,q)=>x*(1-fx)*(1-fy)+y*fx*(1-fy)+z*(1-fx)*fy+q*fx*fy;return[blend(a[0],b[0],c[0],d[0]),blend(a[1],b[1],c[1],d[1])];}
function wind(w,lat,lon,alt,t,bias=[0,0]){const s=state(w,lat,lon,alt,t);return[s[0]+bias[0],s[1]+bias[1]];}
function trajectory(w,p,bias=[0,0]){let lat=p.lat,lon=p.lon,z=p.startAltitude,t=new Date(p.startTime),elapsed=0,total=p.durationHours*3600,dt0=p.stepMinutes*60,pts=[];const push=()=>{const[u,v]=wind(w,lat,lon,z,t,bias),[speed,dir]=uvw(u,v);pts.push({time:iso(t),lat,lon,altitude_m:z,u_mps:u,v_mps:v,wind_speed_mps:speed,wind_direction:dir});};push();while(elapsed<total-1e-9){const dt=Math.min(dt0,total-elapsed);const der=(la,lo,zz,tt)=>{const[u,v]=wind(w,la,lo,zz,tt,bias);return[u,v,zz>=p.maxAltitude?0:p.ascentRate];};const[u1,v1,z1]=der(lat,lon,z,t);let[qLat,qLon]=move(lat,lon,u1*dt/2,v1*dt/2),qZ=Math.min(p.maxAltitude,z+z1*dt/2),qT=new Date(t.getTime()+dt*500);const[u2,v2,z2]=der(qLat,qLon,qZ,qT);[qLat,qLon]=move(lat,lon,u2*dt/2,v2*dt/2);qZ=Math.min(p.maxAltitude,z+z2*dt/2);const[u3,v3,z3]=der(qLat,qLon,qZ,qT);[qLat,qLon]=move(lat,lon,u3*dt,v3*dt);qZ=Math.min(p.maxAltitude,z+z3*dt);const qT4=new Date(t.getTime()+dt*1000);const[u4,v4,z4]=der(qLat,qLon,qZ,qT4);[lat,lon]=move(lat,lon,dt*(u1+2*u2+2*u3+u4)/6,dt*(v1+2*v2+2*v3+v4)/6);z=Math.min(p.maxAltitude,z+dt*(z1+2*z2+2*z3+z4)/6);t=qT4;elapsed+=dt;push();}return pts;}
function percentile(a,p){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),i=(b.length-1)*p,l=Math.floor(i),f=i-l;return b[l]+(b[l+1]??b[l])*f;}
function backTrajectory(w,p,bias=[0,0]){let lat=p.lat,lon=p.lon,z=Math.max(0,p.altitude),t=new Date(p.time),remaining=p.durationHours*3600,elapsed=0,pts=[];const push=()=>{const[u,v]=wind(w,lat,lon,z,t,bias),[sp,di]=uvw(u,v);pts.push({time:iso(t),lat,lon,altitude_m:z,u_mps:u,v_mps:v,wind_speed_mps:sp,wind_direction:di});};push();while(remaining>1e-9&&z>0){const dt=-Math.min(p.stepSeconds,remaining),der=(la,lo,zz,tt)=>{const[u,v]=wind(w,la,lo,zz,tt,bias);return[u,v,p.ascentRate];};const[u1,v1,z1]=der(lat,lon,z,t);let[qLat,qLon]=move(lat,lon,u1*dt/2,v1*dt/2),qZ=Math.max(0,z+z1*dt/2),qT=new Date(t.getTime()+dt*500);const[u2,v2,z2]=der(qLat,qLon,qZ,qT);[qLat,qLon]=move(lat,lon,u2*dt/2,v2*dt/2);qZ=Math.max(0,z+z2*dt/2);const[u3,v3,z3]=der(qLat,qLon,qZ,qT);[qLat,qLon]=move(lat,lon,u3*dt,v3*dt);qZ=Math.max(0,z+z3*dt);const qT4=new Date(t.getTime()+dt*1000);const[u4,v4,z4]=der(qLat,qLon,qZ,qT4);[lat,lon]=move(lat,lon,dt*(u1+2*u2+2*u3+u4)/6,dt*(v1+2*v2+2*v3+v4)/6);z=Math.max(0,z+dt*(z1+2*z2+2*z3+z4)/6);t=qT4;elapsed+=-dt;remaining+=dt;push();}return pts;}
async function runBack(){clearLines();try{const baseTime=new Date(btime.value),hours=Math.max(.05,+bh.value),members=Math.max(20,Math.min(500,+bm.value)),w=await fetchWeather(+blat.value,+blon.value,radius(hours),new Date(baseTime.getTime()-hours*3600000),baseTime),all=[],launch=[];status('Расчёт обратного ансамбля…');progress(5);for(let i=0;i<members;i++){const r=rng(42+i*7919),pts=backTrajectory(w,{lat:+blat.value,lon:+blon.value,time:baseTime,altitude:Math.max(0,+balt.value+gaussian(r)*50),ascentRate:Math.max(.2,(+bas.value||5)+gaussian(r)*.7),durationHours:hours,stepSeconds:Math.max(30,+document.getElementById('bstep')?.value||60)} ,[gaussian(r)*1.5,gaussian(r)*1.5]);all.push(pts);launch.push(pts[pts.length-1]);if(i%2===0){progress(5+85*(i+1)/members);await sleep(0);}}const clat=launch.reduce((s,p)=>s+p.lat,0)/launch.length,clon=launch.reduce((s,p)=>s+p.lon,0)/launch.length,ds=launch.map(p=>dist(clat,clon,p.lat,p.lon)),best=launch[ds.indexOf(Math.min(...ds))];clearLines();all.forEach((p,i)=>line(p,i?'#b8a2d9':'#8a2be2',i?1:3));fitAll();showResult('<b>Оценка запуска:</b> '+best.lat.toFixed(5)+', '+best.lon.toFixed(5)+'<br><b>Ансамбль:</b> '+launch.length+'/'+members+'<br><b>P50:</b> '+Math.round(percentile(ds,.5))+' м<br><b>P80:</b> '+Math.round(percentile(ds,.8))+' м<br><b>P95:</b> '+Math.round(percentile(ds,.95))+' м');status('Готово');progress(100);setTimeout(()=>progress(0,false),500);}catch(e){progress(0,false);status(e.message,true);}}
function pointInPoly(p,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a.lon>p.lon)!=(b.lon>p.lon)&&p.lat<(b.lat-a.lat)*(p.lon-a.lon)/(b.lon-a.lon)+a.lat)inside=!inside;}return inside;}
function segIntersect(a,b,c,d){const o=(p,q,r)=>(q.lon-p.lon)*(r.lat-p.lat)-(q.lat-p.lat)*(r.lon-p.lon);const a1=o(a,b,c),a2=o(a,b,d),b1=o(c,d,a),b2=o(c,d,b);return((a1>0)!=(a2>0))&&((b1>0)!=(b2>0));}
function polyHit(pts,poly){if(!poly||poly.length<3)return false;for(const p of pts)if(pointInPoly(p,poly))return true;for(let i=1;i<pts.length;i++)for(let j=0;j<poly.length;j++)if(segIntersect(pts[i-1],pts[i],poly[j],poly[(j+1)%poly.length]))return true;return false;}
function targetHit(pts,target,radiusM,poly){let min=Infinity,inside=0;for(let i=0;i<pts.length;i++){const p=pts[i],insideNow=poly?pointInPoly(p,poly):dist(p.lat,p.lon,target.lat,target.lon)<=radiusM;if(insideNow)inside+=i?Math.max(0,(new Date(p.time)-new Date(pts[i-1].time))/1000):0;const d=poly?(pointInPoly(p,poly)?0:Infinity):dist(p.lat,p.lon,target.lat,target.lon);if(d<min)min=d;}return{min,inside,hit:poly?polyHit(pts,poly):min<=radiusM};}
function launchPoints(c,r){const out=[c];for(let ring=1;ring<=2;ring++){const rr=r*ring/2,n=12*ring;for(let i=0;i<n;i++){const a=2*Math.PI*i/n;out.push({lat:c.lat+rr*Math.cos(a)/111320,lon:c.lon+rr*Math.sin(a)/(111320*Math.max(.15,Math.cos(rad(c.lat))))});}}return out;}
function surfaceShear(w,p,t,top){const[u1,v1]=wind(w,p.lat,p.lon,10,t),[u2,v2]=wind(w,p.lat,p.lon,Math.max(100,top),t);return[Math.hypot(u1,v1),Math.hypot(u2-u1,v2-v1)/Math.max(1,top-10)];}
function hazard(w,pts,limit){for(const p of pts){const c=w.cells[0],ts=c.hourly.time||[],idx=ts.reduce((bi,x,i)=>Math.abs(new Date(x+'Z')-new Date(p.time))<Math.abs(new Date(ts[bi]+'Z')-new Date(p.time))?i:bi,0),code=c.hourly.weather_code?.[idx],rain=c.hourly.precipitation?.[idx]??0;if([95,96,99].includes(+code)||+rain>limit)return true;}return false;}
async function runFav(){clearLines();try{const target={lat:+tlat.value,lon:+tlon.value},center={lat:+clat.value,lon:+clon.value},start=new Date(fs.value),end=new Date(fe.value),duration=Math.max(.1,+fh.value),launchR=Math.max(100,+fr.value),targetR=Math.max(100,+ftr.value),stepH=Math.max(.25,+fts.value),ens=Math.max(5,Math.min(150,+fens.value)),maxAlt=+fmax.value,ascent=+fas.value,w=await fetchWeather((target.lat+center.lat)/2,(target.lon+center.lon)/2,Math.max(600,radius(duration)+launchR/1000),start,new Date(end.getTime()+duration*3600000)),points=launchPoints(center,launchR),candidates=[];status('Поиск окон запуска…');progress(3);for(let t=start.getTime();t<=end.getTime();t+=stepH*3600000){for(const lp of points){const[sw,sh]=surfaceShear(w,lp,new Date(t),maxAlt);if(sw>+fwind.value||sh>+fshear.value)continue;const pts=trajectory(w,{lat:lp.lat,lon:lp.lon,startAltitude:0,ascentRate:ascent,maxAltitude:maxAlt,durationHours:duration,stepMinutes:2,startTime:new Date(t)}),q=targetHit(pts,target,targetR,null);if(q.hit&&!hazard(w,pts,+frain.value))candidates.push({launch_time:iso(new Date(t)),launch_point:lp,trajectory:pts,min_distance_to_target_m:q.min,time_in_target_s:q.inside,surface_wind_mps:sw,shear_s_inv:sh});await sleep(0);}}for(let ci=0;ci<candidates.length;ci++){const c=candidates[ci],results=[];for(let m=0;m<ens;m++){const r=rng(1009*m+ci),pts=trajectory(w,{lat:c.launch_point.lat,lon:c.launch_point.lon,startAltitude:0,ascentRate:ascent,maxAltitude:maxAlt,durationHours:duration,stepMinutes:2,startTime:new Date(c.launch_time)},[gaussian(r)*1.5,gaussian(r)*1.5]),q=targetHit(pts,target,targetR,null);if(q.hit&&!hazard(w,pts,+frain.value))results.push(q.min);}c.ensemble_success_rate=results.length/ens;c.ensemble_median_distance_m=percentile(results,.5);c.ensemble_p90_distance_m=percentile(results,.9);c.score=(c.ensemble_median_distance_m||1e9)/Math.max(100,targetR)-Math.min(c.time_in_target_s/3600,2)*.15+(c.surface_wind_mps/+fwind.value)*.05+(c.shear_s_inv/+fshear.value)*.05;}candidates.sort((a,b)=>a.score-b.score);const top=candidates.slice(0,20);clearLines();top.forEach((x,i)=>line(x.trajectory,i?'#ff8a80':'#e53935',i?2:4));fitAll();showResult('<b>Найдено кандидатов:</b> '+candidates.length+(top.length?'<br><b>Рекомендуемое:</b> '+new Date(top[0].launch_time).toLocaleString():'') );status('Готово');progress(100);setTimeout(()=>progress(0,false),500);}catch(e){progress(0,false);status(e.message,true);}}
async function runDirect(){clearLines();try{const p={lat:+dlat.value,lon:+dlon.value,startAltitude:+dalt.value,ascentRate:+das.value,maxAltitude:+dmax.value,durationHours:+dh.value,stepMinutes:5,startTime:new Date(dtime.value)},w=await fetchWeather(p.lat,p.lon,radius(p.durationHours),new Date(p.startTime),new Date(p.startTime.getTime()+p.durationHours*3600000)),pts=trajectory(w,p);line(pts);fitAll();showResult('<b>Точек:</b> '+pts.length+'<br><b>Конечная высота:</b> '+Math.round(pts[pts.length-1].altitude_m)+' м');status('Готово');progress(100);setTimeout(()=>progress(0,false),500);}catch(e){progress(0,false);status(e.message,true);}}
window.direct=runDirect;window.back=runBack;window.fav=runFav;
})();
