<?php
require_once __DIR__.'/core1.php';
require_once __DIR__.'/core2.php';
require_once __DIR__.'/core3.php';
?>
<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Weter — атмосферное моделирование</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<style>
*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#17202a;background:#eef2f5}.app{display:grid;grid-template-columns:390px 1fr;height:100vh}.side{background:#fff;padding:18px;overflow:auto;box-shadow:2px 0 12px #0001;z-index:2}.tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin:16px 0}.tabs button{border:0;background:#e9edf1;padding:11px 5px;border-radius:8px;cursor:pointer}.tabs button.active{background:#17202a;color:#fff}.panel{display:none}.panel.active{display:block}.row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.step{margin:15px 0 8px;font-weight:700}label{display:block;font-size:12px;margin:8px 0}input,select,button{font:inherit}input,select{width:100%;padding:9px;border:1px solid #ccd3d9;border-radius:7px;margin-top:4px}button.action{width:100%;padding:12px;border:0;border-radius:8px;background:#1f6feb;color:white;cursor:pointer;margin-top:12px}.secondary{width:100%;padding:9px;border:1px solid #ccd3d9;background:#f6f8fa;border-radius:7px;cursor:pointer;margin-top:5px}.status{margin-top:12px;font-size:13px;min-height:20px}.result{margin-top:12px;font-size:13px}.window{border-top:1px solid #ddd;padding:9px 0}.map{height:100%;width:100%}.hint{position:absolute;top:12px;right:12px;background:#fff;padding:8px 12px;border-radius:7px;z-index:1000;box-shadow:0 2px 8px #0002}
</style></head><body><div class="app"><aside class="side"><h2 style="margin:0">Weter</h2><div style="font-size:12px;color:#667">АТМОСФЕРНОЕ МОДЕЛИРОВАНИЕ</div>
<div class="tabs"><button class="tab active" data-panel="direct">Прямая</button><button class="tab" data-panel="back">Обратная</button><button class="tab" data-panel="fav">Окно запуска</button></div>
<section id="direct" class="panel active"><div class="step">1. Точка старта</div><div class="row"><label>Широта<input id="dlat" value="44.67" type="number" step="0.000001"></label><label>Долгота<input id="dlon" value="34.41" type="number" step="0.000001"></label></div><button class="secondary" onclick="pick('direct')">Выбрать на карте</button><div class="step">2. Параметры</div><label>Время запуска<input id="dtime" type="datetime-local"></label><label>Горизонт<select id="dh"><option>6</option><option>12</option><option selected>24</option><option>48</option><option>72</option><option>168</option></select></label><div class="row"><label>Высота, м<input id="dalt" value="0" type="number"></label><label>Набор, м/с<input id="das" value="5" type="number" step="0.1"></label></div><label>Макс. высота, м<input id="dmax" value="10000" type="number"></label><button class="action" onclick="direct()">Рассчитать траекторию</button></section>
<section id="back" class="panel"><div class="step">1. Точка обнаружения</div><div class="row"><label>Широта<input id="blat" value="44.67" type="number" step="0.000001"></label><label>Долгота<input id="blon" value="34.41" type="number" step="0.000001"></label></div><button class="secondary" onclick="pick('back')">Выбрать на карте</button><div class="step">2. Параметры</div><label>Время обнаружения<input id="btime" type="datetime-local"></label><label>Высота, м<input id="balt" value="10000" type="number"></label><div class="row"><label>Набор, м/с<input id="bas" value="5" type="number" step="0.1"></label><label>Глубина, ч<input id="bh" value="4" type="number"></label></div><label>Ансамбль<input id="bm" value="150" type="number"></label><button class="action" onclick="back()">Найти возможный запуск</button></section>
<section id="fav" class="panel"><div class="step">1. Цель</div><div class="row"><label>Широта<input id="tlat" value="44.70" type="number" step="0.000001"></label><label>Долгота<input id="tlon" value="34.50" type="number" step="0.000001"></label></div><button class="secondary" onclick="pick('target')">Указать цель на карте</button><div class="step">2. Центр зоны запуска</div><div class="row"><label>Широта<input id="clat" value="44.67" type="number" step="0.000001"></label><label>Долгота<input id="clon" value="34.41" type="number" step="0.000001"></label></div><button class="secondary" onclick="pick('launch')">Указать центр на карте</button><div class="step">3. Период</div><div class="row"><label>От<input id="fs" type="datetime-local"></label><label>До<input id="fe" type="datetime-local"></label></div><div class="row"><label>Радиус запуска, м<input id="fr" value="1000" type="number"></label><label>Допуск цели, м<input id="ftr" value="5000" type="number"></label></div><div class="row"><label>Набор, м/с<input id="fas" value="5" type="number" step="0.1"></label><label>Макс. высота, м<input id="fmax" value="9000" type="number"></label></div><div class="row"><label>Полёт, ч<input id="fh" value="5" type="number" step="0.5"></label><label>Шаг запуска, ч<input id="fts" value="1" type="number" step="0.5"></label></div><button class="action" onclick="fav()">Найти окна запуска</button></section>
<div id="status" class="status"></div><div id="result" class="result"></div></aside><main><div id="map" class="map"></div><div class="hint">Клик по карте выбирает точку активного режима</div></main></div>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
const map=L.map('map').setView([44.67,34.41],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);let mode='direct',marker=null,lines=[];
const now=new Date();const local=d=>new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);dtime.value=local(now);btime.value=local(now);fs.value=local(now);fe.value=local(new Date(now.getTime()+6*3600000));
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.getElementById(b.dataset.panel).classList.add('active');mode=b.dataset.panel});
function status(s,err=false){document.getElementById('status').textContent=s;document.getElementById('status').style.color=err?'#c00':''}function clearLines(){lines.forEach(x=>map.removeLayer(x));lines=[]}function line(points,color='#1f6feb',weight=3){const l=L.polyline(points.map(p=>[p.lat,p.lon]),{color,weight}).addTo(map);lines.push(l);map.fitBounds(l.getBounds().pad(.15));return l}
function pick(m){mode=m;status('Кликните по карте');map.once('click',e=>{const la=e.latlng.lat.toFixed(6),lo=e.latlng.lng.toFixed(6);if(m==='direct'){dlat.value=la;dlon.value=lo}else if(m==='back'){blat.value=la;blon.value=lo}else if(m==='target'){tlat.value=la;tlon.value=lo}else{clat.value=la;clon.value=lo}if(marker)map.removeLayer(marker);marker=L.marker([+la,+lo]).addTo(map);status('Точка установлена')})}
async function post(action,data){status('Расчёт…');const r=await fetch('?api='+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok||j.status==='error')throw Error(j.detail||'Ошибка расчёта');return j}
function showResult(html){document.getElementById('result').innerHTML=html}
async function direct(){clearLines();try{const j=await post('trajectory',{start:{lat:+dlat.value,lon:+dlon.value},start_time:new Date(dtime.value).toISOString(),start_altitude:+dalt.value,ascent_rate:+das.value,max_altitude:+dmax.value,duration_hours:+dh.value,step_minutes:5});line(j.trajectory.map(p=>p), '#1f6feb');showResult('<b>Точек:</b> '+j.trajectory.length);status('Готово')}catch(e){status(e.message,true)}}
async function back(){clearLines();try{const j=await post('backtrajectory',{detection:{lat:+blat.value,lon:+blon.value},detection_time:new Date(btime.value).toISOString(),altitude:+balt.value,ascent_rate:+bas.value,duration_hours:+bh.value,step_minutes:1,members:+bm.value});line(j.result.trajectory.map(p=>p),'#8a2be2');showResult('<b>Оценка запуска:</b> '+j.result.launch_estimate.lat.toFixed(5)+', '+j.result.launch_estimate.lon.toFixed(5));status('Готово')}catch(e){status(e.message,true)}}
async function fav(){clearLines();try{const j=await post('favorable',{target:{lat:+tlat.value,lon:+tlon.value},launch_center:{lat:+clat.value,lon:+clon.value},search_start:new Date(fs.value).toISOString(),search_end:new Date(fe.value).toISOString(),launch_radius_m:+fr.value,target_radius_m:+ftr.value,duration_hours:+fh.value,time_step_hours:+fts.value,ascent_rate:+fas.value,max_altitude:+fmax.value,step_minutes:2});j.windows.forEach(w=>line(w.trajectory,'#e53935',3));showResult('<b>Найдено окон:</b> '+j.count+(j.count?'<br>Красным показаны траектории найденных окон до входа в цель.':''));status('Готово')}catch(e){status(e.message,true)}}
</script></body></html>
