<?php
require_once __DIR__.'/core1.php';
require_once __DIR__.'/core2.php';
require_once __DIR__.'/core3.php';
if(isset($_GET['api'])) api();
?>
<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Weter — атмосферное моделирование</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;color:#17202a;background:#eef2f5}.app{display:grid;grid-template-columns:430px 1fr;height:100vh}.side{background:#fff;padding:18px;overflow:auto;box-shadow:2px 0 12px #0001;z-index:2}.tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin:16px 0}.tabs button{border:0;background:#e9edf1;padding:11px 5px;border-radius:8px;cursor:pointer}.tabs button.active{background:#17202a;color:#fff}.panel{display:none}.panel.active{display:block}.row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.step{margin:15px 0 8px;font-weight:700}label{display:block;font-size:12px;margin:8px 0}input,select,button{font:inherit}input,select{width:100%;padding:9px;border:1px solid #ccd3d9;border-radius:7px;margin-top:4px}button.action{width:100%;padding:12px;border:0;border-radius:8px;background:#1f6feb;color:#fff;cursor:pointer;margin-top:12px}.secondary{width:100%;padding:9px;border:1px solid #ccd3d9;background:#f6f8fa;border-radius:7px;cursor:pointer;margin-top:5px}.status{margin-top:12px;font-size:13px;min-height:22px}.progress{height:7px;background:#e7ebef;border-radius:9px;overflow:hidden;margin-top:7px;display:none}.progress i{display:block;height:100%;width:0;background:#1f6feb;transition:width .25s}.result{margin-top:12px;font-size:13px}.window{border-top:1px solid #ddd;padding:9px 0}.map{height:100%;width:100%}.hint{position:absolute;top:12px;right:12px;background:#fff;padding:8px 12px;border-radius:7px;z-index:1000;box-shadow:0 2px 8px #0002}.note{font-size:11px;color:#667;margin-top:6px}.advanced{border:1px solid #d8dde2;border-radius:9px;padding:10px;margin-top:12px}.advanced summary{cursor:pointer;font-weight:700}.opt{display:grid;grid-template-columns:20px 1fr;gap:7px;align-items:start;margin:10px 0}.opt input[type=checkbox]{width:auto;margin:3px 0}.opt .field{display:grid;grid-template-columns:1fr 90px;gap:7px;align-items:center}.opt .field input{margin:0}.levels{font-size:11px;color:#667;background:#f5f7f9;border-radius:7px;padding:8px;margin-top:8px;line-height:1.5}
.trajectory-info{position:fixed;display:none;width:430px;max-width:calc(100vw - 24px);padding:12px;background:#fff;border:1px solid #d8dde2;border-radius:10px;box-shadow:0 6px 24px #0003;z-index:10000;pointer-events:auto;font-size:12px}.trajectory-info h4{margin:0 0 8px;font-size:14px}.trajectory-stats{display:grid;grid-template-columns:1fr 1fr;gap:4px 12px;margin-bottom:8px}.trajectory-chart{width:100%;height:130px;display:block;border:1px solid #edf0f2;border-radius:6px;background:#fafbfc;margin-top:7px}.trajectory-chart-title{font-size:11px;color:#667;margin-top:7px}.trajectory-point{white-space:nowrap}.trajectory-close{float:right;border:0;background:none;padding:0 0 0 8px;cursor:pointer;font-size:16px;color:#667}
@media(max-width:850px){.app{grid-template-columns:1fr;height:auto;min-height:100vh}.side{position:relative;max-height:none}.map{height:55vh}.hint{display:none}}
</style></head><body><div class="app"><aside class="side"><h2 style="margin:0">Weter</h2><div style="font-size:12px;color:#667">АТМОСФЕРНОЕ МОДЕЛИРОВАНИЕ · PHP / Timeweb</div>
<div class="tabs"><button class="tab active" data-panel="direct">Прямая</button><button class="tab" data-panel="back">Обратная</button><button class="tab" data-panel="fav">Окно запуска</button></div>
<section id="direct" class="panel active"><div class="step">1. Точка старта</div><div class="row"><label>Широта<input id="dlat" value="44.67" type="number" step="0.000001"></label><label>Долгота<input id="dlon" value="34.41" type="number" step="0.000001"></label></div><button class="secondary" onclick="pick('direct')">Выбрать на карте</button><div class="step">2. Параметры</div><label>Время запуска<input id="dtime" type="datetime-local"></label><label>Горизонт<select id="dh"><option>6</option><option>12</option><option selected>24</option><option>48</option><option>72</option><option>168</option></select></label><div class="row"><label>Высота, м<input id="dalt" value="0" type="number"></label><label>Набор, м/с<input id="das" value="5" type="number" step="0.1"></label></div><label>Макс. высота, м<input id="dmax" value="10000" type="number"></label><button class="action" onclick="direct()">Рассчитать траекторию</button></section>
<section id="back" class="panel"><div class="step">1. Точка обнаружения</div><div class="row"><label>Широта<input id="blat" value="44.67" type="number" step="0.000001"></label><label>Долгота<input id="blon" value="34.41" type="number" step="0.000001"></label></div><button class="secondary" onclick="pick('back')">Выбрать на карте</button><div class="step">2. Параметры</div><label>Время обнаружения<input id="btime" type="datetime-local"></label><label>Высота, м<input id="balt" value="10000" type="number"></label><div class="row"><label>Набор, м/с<input id="bas" value="5" type="number" step="0.1"></label><label>Глубина, ч<input id="bh" value="4" type="number"></label></div><label>Ансамбль<input id="bm" value="150" type="number" min="20" max="150"></label><button class="action" onclick="back()">Найти возможный запуск</button></section>
<section id="fav" class="panel"><div class="step">1. Цель</div><div class="row"><label>Широта<input id="tlat" value="44.70" type="number" step="0.000001"></label><label>Долгота<input id="tlon" value="34.50" type="number" step="0.000001"></label></div><button class="secondary" onclick="pick('target')">Указать на карте</button><div class="step">2. Точка старта</div><div class="row"><label>Широта<input id="clat" value="44.67" type="number" step="0.000001"></label><label>Долгота<input id="clon" value="34.41" type="number" step="0.000001"></label></div><button class="secondary" onclick="pick('launch')">Указать центр на карте</button><div class="note">Высота не выбирается вручную: окно запуска проверяется по всем pressure-level источника — 1000, 975, 950, 925, 900, 850, 800, 700, 600, 550, 500, 450, 400, 350 и 300 hPa.</div>
<details class="advanced"><summary>Дополнительные настройки — учитываются только при установленной галочке</summary>
<div class="opt"><input id="fa_period" type="checkbox"><div class="field"><span>Период поиска</span><span></span></div></div><div class="row"><label>От<input id="fs" type="datetime-local"></label><label>До<input id="fe" type="datetime-local"></label></div>
<div class="opt"><input id="fa_launch_radius" type="checkbox"><div class="field"><span>Радиус зоны старта, м</span><input id="fr" value="1000" type="number"></div></div>
<div class="opt"><input id="fa_target_radius" type="checkbox"><div class="field"><span>Допуск попадания, м</span><input id="ftr" value="5000" type="number"></div></div>
<div class="opt"><input id="fa_ascent" type="checkbox"><div class="field"><span>Скорость набора, м/с</span><input id="fas" value="5" type="number" step="0.1"></div></div>
<div class="opt"><input id="fa_flight" type="checkbox"><div class="field"><span>Длительность полёта, ч</span><input id="fh" value="5" type="number" step="0.5"></div></div>
<div class="opt"><input id="fa_wind" type="checkbox"><div class="field"><span>Поверхностный ветер ≤, м/с</span><input id="fwind" value="10" type="number" step="0.1"></div></div>
<div class="opt"><input id="fa_shear" type="checkbox"><div class="field"><span>Сдвиг ветра ≤, 1/с</span><input id="fshear" value="0.002" type="number" step="0.0001"></div></div>
<div class="opt"><input id="fa_rain" type="checkbox"><div class="field"><span>Осадки ≤, мм/ч</span><input id="frain" value="5" type="number" step="0.1"></div></div>
<div class="opt"><input id="fa_ensemble" type="checkbox"><div class="field"><span>Ансамбль запусков</span><input id="fens" value="20" type="number" min="5" max="50"></div></div>
<div class="levels">Высотный перебор всегда активен и не является фильтром. Для каждого времени проверяются все 15 pressure levels; в результате показываются давление и соответствующая geopotential height.</div>
</details><button class="action" onclick="fav()">Найти окна запуска</button></section>
<div id="status" class="status"></div><div class="progress" id="progress"><i></i></div><div id="result" class="result"></div></aside><main><div id="map" class="map"></div><div class="hint">Клик по карте выбирает точку активного режима</div></main></div>
<div id="trajectoryInfo" class="trajectory-info"></div>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
const map=L.map('map').setView([44.67,34.41],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);let mode='direct',lines=[],targetMarker=null,launchMarker=null;const now=new Date();const local=d=>new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);dtime.value=local(now);btime.value=local(now);fs.value=local(now);fe.value=local(new Date(now.getTime()+6*3600000));
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.getElementById(b.dataset.panel).classList.add('active');mode=b.dataset.panel});
function status(s,err=false){document.getElementById('status').textContent=s;document.getElementById('status').style.color=err?'#c00':''}function progress(v,show=true){const p=document.getElementById('progress');p.style.display=show?'block':'none';p.firstElementChild.style.width=Math.max(0,Math.min(100,v))+'%'}function clearLines(){lines.forEach(x=>map.removeLayer(x));lines=[];hideTrajectoryInfo()}function esc(v){return String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]))}
const trajectoryInfo=document.getElementById('trajectoryInfo');let trajectoryInfoTimer=null;
function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function trajectoryValue(p,keys,d=0){for(const k of keys){if(p&&p[k]!=null&&Number.isFinite(Number(p[k])))return Number(p[k]);}return d}
function chartSvg(points,keyKeys,label,unit){const vals=points.map(p=>trajectoryValue(p,keyKeys)).filter(Number.isFinite);if(vals.length<2)return '<div class="note">Недостаточно точек для графика.</div>';const w=400,h=120,pad=24,min=Math.min(...vals),max=Math.max(...vals),range=Math.max(1e-9,max-min);const path=points.map((p,i)=>{const v=trajectoryValue(p,keyKeys);const x=pad+(w-2*pad)*i/Math.max(1,points.length-1);const y=h-pad-(h-2*pad)*(v-min)/range;return (i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)}).join(' ');const mid=(min+max)/2;return '<div class="trajectory-chart-title">'+esc(label)+' ('+esc(unit)+')</div><svg class="trajectory-chart" viewBox="0 0 '+w+' '+h+'" preserveAspectRatio="none"><line x1="'+pad+'" y1="'+pad+'" x2="'+pad+'" y2="'+(h-pad)+'" stroke="#cfd6dc"/><line x1="'+pad+'" y1="'+(h-pad)+'" x2="'+(w-pad)+'" y2="'+(h-pad)+'" stroke="#cfd6dc"/><path d="'+path+'" fill="none" stroke="#1f6feb" stroke-width="2"/><text x="3" y="'+(pad+4)+'" font-size="9" fill="#667">'+max.toFixed(0)+'</text><text x="3" y="'+(h-pad)+'" font-size="9" fill="#667">'+min.toFixed(0)+'</text><text x="'+(w-45)+'" y="'+(h-4)+'" font-size="9" fill="#667">'+esc(points[points.length-1].time?new Date(points[points.length-1].time).toLocaleTimeString():'')+'</text><text x="'+(w/2-18)+'" y="'+(h-4)+'" font-size="9" fill="#667">'+esc(points[0].time?new Date(points[0].time).toLocaleTimeString():'')+'</text></svg>'}
function showTrajectoryInfo(points,title,ev){if(!points||points.length<2)return;const alts=points.map(p=>trajectoryValue(p,['altitude_m','altitude'])),speeds=points.map(p=>trajectoryValue(p,['speed_mps','wind_speed_mps','ground_speed_mps']));const first=points[0],last=points[points.length-1],maxAlt=Math.max(...alts),maxSpeed=Math.max(...speeds);trajectoryInfo.innerHTML='<button class="trajectory-close" onclick="hideTrajectoryInfo()">×</button><h4>'+esc(title||'Траектория')+'</h4><div class="trajectory-stats"><div><b>Начало:</b> '+esc(first.time?new Date(first.time).toLocaleString():'—')+'</div><div><b>Конец:</b> '+esc(last.time?new Date(last.time).toLocaleString():'—')+'</div><div><b>Высота в конце:</b> '+Math.round(alts[alts.length-1])+' м</div><div><b>Макс. высота:</b> '+Math.round(maxAlt)+' м</div><div><b>Скорость в конце:</b> '+speeds[speeds.length-1].toFixed(2)+' м/с</div><div><b>Макс. скорость:</b> '+maxSpeed.toFixed(2)+' м/с</div><div><b>Точек:</b> '+points.length+'</div><div><b>Шаг:</b> '+(points.length>1&&first.time&&last.time?((new Date(last.time)-new Date(first.time))/1000/(points.length-1)/60).toFixed(1)+' мин':'—')+'</div></div>'+chartSvg(points,['altitude_m','altitude'],'Высота','м')+chartSvg(points,['speed_mps','wind_speed_mps','ground_speed_mps'],'Скорость','м/с');trajectoryInfo.style.display='block';positionTrajectoryInfo(ev)}
function positionTrajectoryInfo(ev){if(!ev)return;const margin=12,w=trajectoryInfo.offsetWidth,h=trajectoryInfo.offsetHeight;let x=ev.clientX+16,y=ev.clientY+16;if(x+w>window.innerWidth-margin)x=ev.clientX-w-16;if(y+h>window.innerHeight-margin)y=window.innerHeight-h-margin;trajectoryInfo.style.left=Math.max(margin,x)+'px';trajectoryInfo.style.top=Math.max(margin,y)+'px'}
function hideTrajectoryInfo(){clearTimeout(trajectoryInfoTimer);trajectoryInfo.style.display='none'}
trajectoryInfo.addEventListener('mouseenter',()=>clearTimeout(trajectoryInfoTimer));trajectoryInfo.addEventListener('mouseleave',()=>{trajectoryInfoTimer=setTimeout(hideTrajectoryInfo,180)});
function line(points,color='#1f6feb',weight=3,title='Траектория'){if(!points||points.length<2)return null;const l=L.polyline(points.map(p=>[p.lat,p.lon]),{color,weight}).addTo(map);l._trajectoryPoints=points;l._trajectoryTitle=title;lines.push(l);l.on('mouseover',e=>{l.setStyle({weight:Math.max(weight+2,5)});clearTimeout(trajectoryInfoTimer);showTrajectoryInfo(points,title,e.originalEvent)});l.on('mousemove',e=>{if(trajectoryInfo.style.display==='block')positionTrajectoryInfo(e.originalEvent)});l.on('mouseout',()=>{l.setStyle({weight});trajectoryInfoTimer=setTimeout(hideTrajectoryInfo,220)});return l}function fitAll(){if(lines.length){const g=L.featureGroup(lines);map.fitBounds(g.getBounds().pad(.15))}}
function markPoint(kind,la,lo){const m=L.marker([la,lo]).addTo(map);if(kind==='targetMarker'){if(targetMarker)map.removeLayer(targetMarker);targetMarker=m}else{if(launchMarker)map.removeLayer(launchMarker);launchMarker=m}}
function pick(m){mode=m;status('Кликните по карте');map.once('click',e=>{const la=e.latlng.lat.toFixed(6),lo=e.latlng.lng.toFixed(6);if(m==='direct'){dlat.value=la;dlon.value=lo}else if(m==='back'){blat.value=la;blon.value=lo}else if(m==='target'){tlat.value=la;tlon.value=lo;markPoint('targetMarker',+la,+lo)}else{clat.value=la;clon.value=lo;markPoint('launchMarker',+la,+lo)}status('Точка установлена')})}
</script></body></html>
